### ISSUE TITLE
More containers allocated than instance error

### ISSUE THREAD

**Issue by kartik894** [twitter/heron#1012]
Hi,

I get the following error upon submitting a topology in Heron.
```
Exception in thread "main" java.lang.RuntimeException: More containers allocated than instance. Bailing out.
	at com.twitter.heron.packing.roundrobin.RoundRobinPacking.getBasePacking(RoundRobinPacking.java:246)
	at com.twitter.heron.packing.roundrobin.RoundRobinPacking.pack(RoundRobinPacking.java:57)
	at com.twitter.heron.scheduler.LaunchRunner.call(LaunchRunner.java:121)
	at com.twitter.heron.scheduler.SubmitterMain.callLauncherRunner(SubmitterMain.java:465)
	at com.twitter.heron.scheduler.SubmitterMain.submitTopology(SubmitterMain.java:418)
	at com.twitter.heron.scheduler.SubmitterMain.main(SubmitterMain.java:315)

```
Could you help me with this please? Altering the task resources in heron.aurora isn't solving the problem.

**Comment by maosongfu** [comment]
That means # of containers you specified in topology config is more than
the # of instances.

2016-06-30 5:56 GMT-07:00 Kartik Sathyanarayanan <notifications@github.com>:

> Hi,
>
> I get the following error upon submitting a topology in Heron.
>
> Exception in thread "main" java.lang.RuntimeException: More containers allocated than instance. Bailing out.
>     at com.twitter.heron.packing.roundrobin.RoundRobinPacking.getBasePacking(RoundRobinPacking.java:246)
>     at com.twitter.heron.packing.roundrobin.RoundRobinPacking.pack(RoundRobinPacking.java:57)
>     at com.twitter.heron.scheduler.LaunchRunner.call(LaunchRunner.java:121)
>     at com.twitter.heron.scheduler.SubmitterMain.callLauncherRunner(SubmitterMain.java:465)
>     at com.twitter.heron.scheduler.SubmitterMain.submitTopology(SubmitterMain.java:418)
>     at com.twitter.heron.scheduler.SubmitterMain.main(SubmitterMain.java:315)
>
>
> Could you help me with this please? Altering the task resources in
> heron.aurora isn't solving the problem.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/twitter/heron/issues/1012>, or mute the thread
> <https://github.com/notifications/unsubscribe/AC422hhPVrUKjm5fc-uekvq5NydlUVGBks5qQ70bgaJpZM4JCIS5>
> .
>



-- 
With my best Regards
------------------
Fu Maosong
Twitter Inc.
Mobile: +001-415-244-7520
