### ISSUE TITLE
aurora: Fail to run instances.

### ISSUE THREAD

**Issue by atibon** [twitter/heron#1026]
When I start my heron topology with "heron submit...". I found my topology does not work for a loooooooooong time.

At last, I found the problem in aurora ui. It said that: " THROTTLED : Rescheduled, penalized for 300000 ms for flapping". I don't know y.

I found the error log:

```
ERROR] Regular plan unhealthy!
Traceback (most recent call last):
  File "/root/.pex/install/twitter.common.exceptions-0.3.3-py2-none-any.whl.9c61a23be5d011a66bcc92bc1c10e53e0269a5ad/twitter.common.exceptions-0.3.3-py2-none-any.whl/twitter/common/exceptions/__init__.py", line 126, in _excepting_run
    self.__real_run(*args, **kw)
  File "/root/.pex/install/twitter.common.concurrent-0.3.3-py2-none-any.whl.8771a0a7164b735756035d65d3233afd2066e8ac/twitter.common.concurrent-0.3.3-py2-none-any.whl/twitter/common/concurrent/deferred.py", line 42, in run
    self._closure()
  File "/tmp/mesos/slaves/495601fb-7879-43e9-b8bd-f5dc75294597-S8/frameworks/495601fb-7879-43e9-b8bd-f5dc75294597-0000/executors/thermos-1467688267792-admin-devel-ExclamationTopology2-0-42ca4606-ca4a-43c8-8bc9-62c7a73dfedc/runs/506d9f59-3860-4feb-bcc4-1636cd1adb1c/thermos_executor/apache/aurora/executor/common/announcer.py", line 219, in stop
AttributeError: 'NoneType' object has no attribute 'stop'
```

The other one:

![](https://static.dingtalk.com/media/lALPAWNFeLOBhQnNAYXNArk_697_389.png_620x10000q90.jpg)

Can anybody help me to find the bug?

**Comment by billonahill** [comment]
The flapping thing is aurora saying your process is failing.

The line before the exception at heron-executor.py:359 [outputs](https://github.com/twitter/heron/blob/master/heron/executor/src/python/heron-executor.py#L358) the process that's trying to be run. Check for that in the logs.

**Comment by maosongfu** [comment]
Also, make sure your JAVA_HOME is set correctly.

**Comment by atibon** [comment]
Finally I fix it. That's because the JAVA_HOME of submitting server is not the same to the worker server.
