### ISSUE TITLE
Build failure on local Ubuntu (14.04), "Failed to find setuptools while building pex"

### ISSUE THREAD

**Issue by lewiskan** [twitter/heron#109]
PEX may be Anaconda Python related using version 2.7.6, also re-installed Python using Docker Ubuntu 14.04 instructions including manual installation: python-setuptools.

INFO: From PexPython heron/shell/src/python/heron-shell.pex:
Traceback (most recent call last):
  File "/home/tony/.cache/bazel/_bazel_tony/91ccb56ec8436235118164d4e388a63e/heron/bazel-out/local_linux-fastbuild/bin/3rdparty/pex/_pex.runfiles/3rdparty/pex/_pex.py", line 169, in <module>
    sys.exit(main())
  File "/home/tony/.cache/bazel/_bazel_tony/91ccb56ec8436235118164d4e388a63e/heron/bazel-out/local_linux-fastbuild/bin/3rdparty/pex/_pex.runfiles/3rdparty/pex/_pex.py", line 162, in main
    pex_builder.build(output)
  File "/home/tony/.cache/bazel/_bazel_tony/91ccb56ec8436235118164d4e388a63e/heron/bazel-out/local_linux-fastbuild/bin/3rdparty/pex/_pex.runfiles/3rdparty/pex/pex/pex_builder.py", line 414, in build
    self.freeze(bytecode_compile=bytecode_compile)
  File "/home/tony/.cache/bazel/_bazel_tony/91ccb56ec8436235118164d4e388a63e/heron/bazel-out/local_linux-fastbuild/bin/3rdparty/pex/_pex.runfiles/3rdparty/pex/pex/pex_builder.py", line 398, in freeze
    self._prepare_bootstrap()
  File "/home/tony/.cache/bazel/_bazel_tony/91ccb56ec8436235118164d4e388a63e/heron/bazel-out/local_linux-fastbuild/bin/3rdparty/pex/_pex.runfiles/3rdparty/pex/pex/pex_builder.py", line 358, in _prepare_bootstrap
    raise RuntimeError('Failed to find setuptools while building pex!')
RuntimeError: Failed to find setuptools while building pex!
ERROR: /home/tony/workspace/heron/heron/shell/src/python/BUILD:17:1: null failed: _pex failed: error executing command bazel-out/local_linux-fastbuild/bin/3rdparty/pex/_pex --entry-point heron.shell.src.python.main bazel-out/local_linux-fastbuild/bin/heron/shell/src/python/heron-shell.pex ... (remaining 1 argument(s) skipped).

**Comment by nwangtw** [comment]
is this still a problem?
