### ISSUE TITLE
Error in running "./scripts/setup-intellij.sh"

### ISSUE THREAD

**Issue by yanxz** [twitter/heron#1099]
I got the following error message:

````
ERROR: /Users/syan/code/heron/integration-test/src/python/test_runner/BUILD:5:1: Executing extra_action //tools/python:checkstyle_python on //integration-test/src/python/test_runner:test-runner failed: bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
************* Module main
W:192, 0: TODO: Enable this option (fixme)
C: 21, 0: Line too long (104/100) (line-too-long)
C: 26, 0: Line too long (112/100) (line-too-long)
C: 27, 0: Wrong continued indentation (add 13 spaces).
      params.releasePackageUri, args)
      ^            | (bad-continuation)
C: 37, 0: Wrong hanging indentation (add 2 spaces).
      params.resultsServerHostname,
      ^ | (bad-continuation)
C: 38, 0: Wrong hanging indentation (add 2 spaces).
      params.resultsServerPort,
      ^ | (bad-continuation)
C: 39, 0: Wrong hanging indentation (add 2 spaces).
      topologyName
      ^ | (bad-continuation)
C: 87, 0: Wrong continued indentation (add 11 spaces).
        % (response.status, response.reason, response.read()))
        ^          | (bad-continuation)
C: 94, 0: No space allowed before bracket
  for i in range (0, RETRY_ATTEMPTS):
                 ^ (bad-whitespace)
C:108, 0: No space allowed around keyword argument assignment
def submitTopology(heronCliPath, cluster, role, env, jarPath, classPath, pkgUri, args = None):
                                                                                      ^ (bad-whitespace)
C:115, 0: Wrong hanging indentation (add 2 spaces).
    heronCliPath, cluster, role, env, jarPath, classPath, args)
    ^ | (bad-continuation)
C:123, 0: Unnecessary parens after 'if' keyword (superfluous-parens)
C:133, 0: Wrong hanging indentation (add 2 spaces).
    heronCliPath, cluster, role, env, topologyName)
    ^ | (bad-continuation)
C:137, 0: Unnecessary parens after 'if' keyword (superfluous-parens)
W:141, 0: Bad indentation. Found 7 spaces, expected 6 (bad-indentation)
W:142, 0: Bad indentation. Found 7 spaces, expected 6 (bad-indentation)
W:153, 0: Unnecessary semicolon (unnecessary-semicolon)
C:161, 0: Unnecessary parens after 'if' keyword (superfluous-parens)
C:171, 0: Line too long (101/100) (line-too-long)
C:188, 0: Line too long (114/100) (line-too-long)
C:  1, 0: Missing module docstring (missing-docstring)
C: 20, 0: Missing function docstring (missing-docstring)
W: 29, 4: Specify string format arguments as logging function parameters (logging-not-lazy)
W: 32, 2: Specify string format arguments as logging function parameters (logging-not-lazy)
W: 42, 4: Specify string format arguments as logging function parameters (logging-not-lazy)
W: 55, 4: Specify string format arguments as logging function parameters (logging-not-lazy)
W: 70, 4: Specify string format arguments as logging function parameters (logging-not-lazy)
W: 36, 5: Unused variable 'httpResponseCode' (unused-variable)
C: 79, 0: Missing function docstring (missing-docstring)
W: 81, 4: Specify string format arguments as logging function parameters (logging-not-lazy)
W: 86, 6: Specify string format arguments as logging function parameters (logging-not-lazy)
W: 90, 2: Specify string format arguments as logging function parameters (logging-not-lazy)
C: 93, 0: Missing function docstring (missing-docstring)
W:104, 2: Specify string format arguments as logging function parameters (logging-not-lazy)
W: 94, 6: Unused variable 'i' (unused-variable)
C:108, 0: Missing function docstring (missing-docstring)
W:120, 2: Specify string format arguments as logging function parameters (logging-not-lazy)
W:122, 6: Unused variable 'i' (unused-variable)
C:130, 0: Missing function docstring (missing-docstring)
W:135, 2: Specify string format arguments as logging function parameters (logging-not-lazy)
W:139, 6: Specify string format arguments as logging function parameters (logging-not-lazy)
W:141, 7: Specify string format arguments as logging function parameters (logging-not-lazy)
W:144, 2: Specify string format arguments as logging function parameters (logging-not-lazy)
C:148, 0: Missing function docstring (missing-docstring)
W:159, 4: Specify string format arguments as logging function parameters (logging-not-lazy)
C:168, 0: Missing function docstring (missing-docstring)
W:204, 4: Specify string format arguments as logging function parameters (logging-not-lazy)
W:206, 6: Specify string format arguments as logging function parameters (logging-not-lazy)
W:209, 4: Specify string format arguments as logging function parameters (logging-not-lazy)
W:211, 6: Specify string format arguments as logging function parameters (logging-not-lazy)
W:  7, 0: Unused import threading (unused-import)
W: 10, 0: Unused import mimetools from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import GONE from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import FakeSocket from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import HTTPS_PORT from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import HTTP from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import REQUESTED_RANGE_NOT_SATISFIABLE from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import SERVICE_UNAVAILABLE from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import CannotSendHeader from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import MOVED_PERMANENTLY from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import BadStatusLine from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import UnknownProtocol from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import LENGTH_REQUIRED from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import REQUEST_ENTITY_TOO_LARGE from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import LineAndFileWrapper from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import FOUND from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import array from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import ACCEPTED from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import BAD_GATEWAY from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import REQUEST_TIMEOUT from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import SWITCHING_PROTOCOLS from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import HTTP_PORT from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import EXPECTATION_FAILED from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import USE_PROXY from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import UNAUTHORIZED from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import HTTPException from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import REQUEST_URI_TOO_LONG from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import HTTP_VERSION_NOT_SUPPORTED from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import warnings from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import IM_USED from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import InvalidURL from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import SEE_OTHER from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import re from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import UNPROCESSABLE_ENTITY from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import BAD_REQUEST from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import GATEWAY_TIMEOUT from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import py3kwarning from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import IncompleteRead from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import FAILED_DEPENDENCY from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import MULTIPLE_CHOICES from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import INSUFFICIENT_STORAGE from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import PAYMENT_REQUIRED from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import CONFLICT from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import responses from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import LineTooLong from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import TEMPORARY_REDIRECT from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import MAXAMOUNT from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import INTERNAL_SERVER_ERROR from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import PARTIAL_CONTENT from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import CREATED from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import RESET_CONTENT from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import PROCESSING from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import PRECONDITION_FAILED from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import NOT_MODIFIED from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import ResponseNotReady from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import ssl from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import UnknownTransferEncoding from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import NOT_ACCEPTABLE from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import UNSUPPORTED_MEDIA_TYPE from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import HTTPS from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import HTTPResponse from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import NotConnected from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import OK from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import NOT_FOUND from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import MULTI_STATUS from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import urlsplit from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import NOT_EXTENDED from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import NON_AUTHORITATIVE_INFORMATION from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import LOCKED from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import socket from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import UnimplementedFileMode from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import METHOD_NOT_ALLOWED from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import StringIO from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import NO_CONTENT from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import ImproperConnectionState from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import NOT_IMPLEMENTED from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import CONTINUE from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import HTTPMessage from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import error from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import HTTPSConnection from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import PROXY_AUTHENTICATION_REQUIRED from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import CannotSendRequest from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import UPGRADE_REQUIRED from wildcard import (unused-wildcard-import)
W: 10, 0: Unused import FORBIDDEN from wildcard import (unused-wildcard-import)
Jul 17, 2016 9:39:15 PM com.twitter.bazel.checkstyle.PythonCheckstyle main
INFO: 1 python files found by checkstyle
Exception in thread "main" java.lang.RuntimeException: python checkstyle command failed with status 20
	at com.twitter.bazel.checkstyle.PythonCheckstyle.runLinter(PythonCheckstyle.java:119)
	at com.twitter.bazel.checkstyle.PythonCheckstyle.main(PythonCheckstyle.java:88)
````

**Comment by objmagic** [comment]
@yanxz Hi, Python style checking was just enabled yesterday and I am sorry I forgot fix Python coding style under ``integration_test``.

will do it now.

**Comment by objmagic** [comment]
Thanks for the issue. A PR has been submitted to fix this issue: https://github.com/twitter/heron/pull/1100

**Comment by objmagic** [comment]
Hi, @yanxz 

#1100 is merged. Could you please pull the master branch, do ``bazel clean``, and try again?

**Comment by yanxz** [comment]
@objmagic pulled the change and reran the script, it works now! Thanks for such quick response, it's really awesome!
