### ISSUE TITLE
Error in running 'heron-shell' on YARN MODE

### ISSUE THREAD

**Issue by mycFelix** [twitter/heron#1103]
hi
I ran an example topology named ExclamationTopology on YARN MODE. 
The topology was always killed by itself after running a while,and i cant open the log&job page on Heron-ui.
I checked the `heron-executor.stdout` log. Maybe the reason is:
````
2016-07-18 16:02:16: Running heron-shell-1 process as ./heron-core/bin/heron-shell --port=28157 --log_file_prefix=log-files/heron-shell.log
2016-07-18 16:02:16: Logging pid 99339 to file heron-shell-1.pid
2016-07-18 16:02:16: heron-shell-1 exited with status 256
2016-07-18 16:02:16: heron-shell-1 stdout:
2016-07-18 16:02:16: heron-shell-1 stderr: Traceback (most recent call last):
  File "/data7/yarn/local/usercache/miaoyichen/appcache/application_1468545858776_0011/container_1468545858776_0011_01_000003/heron-core/bin/heron-shell/.bootstrap/_pex/pex.py", line 313, in execute
  File "/data7/yarn/local/usercache/miaoyichen/appcache/application_1468545858776_0011/container_1468545858776_0011_01_000003/heron-core/bin/heron-shell/.bootstrap/_pex/pex.py", line 78, in _activate
  File "/data7/yarn/local/usercache/miaoyichen/appcache/application_1468545858776_0011/container_1468545858776_0011_01_000003/heron-core/bin/heron-shell/.bootstrap/_pex/environment.py", line 132, in activate
  File "/data7/yarn/local/usercache/miaoyichen/appcache/application_1468545858776_0011/container_1468545858776_0011_01_000003/heron-core/bin/heron-shell/.bootstrap/_pex/environment.py", line 176, in _activate
  File "/data7/yarn/local/usercache/miaoyichen/appcache/application_1468545858776_0011/container_1468545858776_0011_01_000003/heron-core/bin/heron-shell/.bootstrap/_pex/environment.py", line 121, in update_candidate_distributions
  File "/data7/yarn/local/usercache/miaoyichen/appcache/application_1468545858776_0011/container_1468545858776_0011_01_000003/heron-core/bin/heron-shell/.bootstrap/_pex/environment.py", line 107, in load_internal_cache
  File "/data7/yarn/local/usercache/miaoyichen/appcache/application_1468545858776_0011/container_1468545858776_0011_01_000003/heron-core/bin/heron-shell/.bootstrap/_pex/environment.py", line 95, in write_zipped_internal_cache
  File "/data7/yarn/local/usercache/miaoyichen/appcache/application_1468545858776_0011/container_1468545858776_0011_01_000003/heron-core/bin/heron-shell/.bootstrap/_pex/util.py", line 174, in cache_distribution
  File "/data7/yarn/local/usercache/miaoyichen/appcache/application_1468545858776_0011/container_1468545858776_0011_01_000003/heron-core/bin/heron-shell/.bootstrap/_pex/common.py", line 115, in safe_open
  File "/data7/yarn/local/usercache/miaoyichen/appcache/application_1468545858776_0011/container_1468545858776_0011_01_000003/heron-core/bin/heron-shell/.bootstrap/_pex/common.py", line 103, in safe_mkdir
  File "/usr/lib64/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib64/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib64/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib64/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib64/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/home/.pex'

2016-07-18 16:02:16: heron-shell-1 exited too many times
2016-07-18 16:02:16: Executor terminated; exiting all process in executor.
````
Seems `heron-shell` is not started.

My Python version is `Python 2.7.5`. I've no idea about the OSError `/home/.pex`.

**Comment by mycFelix** [comment]
so.... I need to execute 'chmod 777 /home/.pex'? 

Is there any other way?

**Comment by ashvina** [comment]
I think #1010 is similar to this issue?
I will investigate the deployment flow for non admin user accounts.

**Comment by mycFelix** [comment]
@ashvina - thank you for your reply. I didn't notice #1010 issue. It seems we get the same problem on `incorrect $HOME env`.  I will change admin user accounts and try it again. I hope this problem could be fixed in the next version. I will close this issue. Thank you AGAIN.

**Comment by mycFelix** [comment]
@ashvina - I installed heron on admin user account and tried it again. And I got the same error when I ran topo on Yarn mode.

The $HERON_HOME is located at `/usr/local/heron` and my `hdfs` user $HOME is `/home/hdfs`.

my shell command is following:
````
[hdfs ~]$ heron submit yarn /usr/local/heron/examples/heron-examples.jar com.twitter.heron.examples.ExclamationTopology ExclamationTopology
````

The error log is following:
````
2016-07-19 14:49:25: Running heron-shell-1 process as ./heron-core/bin/heron-shell --port=48529 --log_file_prefix=log-files/heron-shell.log
2016-07-19 14:49:25: Logging pid 30749 to file heron-shell-1.pid
2016-07-19 14:49:25: heron-shell-1 exited with status 256
2016-07-19 14:49:25: heron-shell-1 stdout:
2016-07-19 14:49:25: heron-shell-1 stderr: Traceback (most recent call last):
  File "/data9/yarn/local/usercache/hdfs/appcache/application_1468545858776_0023/container_1468545858776_0023_01_000003/heron-core/bin/heron-shell/.bootstrap/_pex/pex.py", line 313, in execute
  File "/data9/yarn/local/usercache/hdfs/appcache/application_1468545858776_0023/container_1468545858776_0023_01_000003/heron-core/bin/heron-shell/.bootstrap/_pex/pex.py", line 78, in _activate
  File "/data9/yarn/local/usercache/hdfs/appcache/application_1468545858776_0023/container_1468545858776_0023_01_000003/heron-core/bin/heron-shell/.bootstrap/_pex/environment.py", line 132, in activate
  File "/data9/yarn/local/usercache/hdfs/appcache/application_1468545858776_0023/container_1468545858776_0023_01_000003/heron-core/bin/heron-shell/.bootstrap/_pex/environment.py", line 176, in _activate
  File "/data9/yarn/local/usercache/hdfs/appcache/application_1468545858776_0023/container_1468545858776_0023_01_000003/heron-core/bin/heron-shell/.bootstrap/_pex/environment.py", line 121, in update_candidate_distributions
  File "/data9/yarn/local/usercache/hdfs/appcache/application_1468545858776_0023/container_1468545858776_0023_01_000003/heron-core/bin/heron-shell/.bootstrap/_pex/environment.py", line 107, in load_internal_cache
  File "/data9/yarn/local/usercache/hdfs/appcache/application_1468545858776_0023/container_1468545858776_0023_01_000003/heron-core/bin/heron-shell/.bootstrap/_pex/environment.py", line 95, in write_zipped_internal_cache
  File "/data9/yarn/local/usercache/hdfs/appcache/application_1468545858776_0023/container_1468545858776_0023_01_000003/heron-core/bin/heron-shell/.bootstrap/_pex/util.py", line 174, in cache_distribution
  File "/data9/yarn/local/usercache/hdfs/appcache/application_1468545858776_0023/container_1468545858776_0023_01_000003/heron-core/bin/heron-shell/.bootstrap/_pex/common.py", line 115, in safe_open
  File "/data9/yarn/local/usercache/hdfs/appcache/application_1468545858776_0023/container_1468545858776_0023_01_000003/heron-core/bin/heron-shell/.bootstrap/_pex/common.py", line 103, in safe_mkdir
  File "/usr/lib64/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib64/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib64/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib64/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib64/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/home/.pex'
````

**Comment by maosongfu** [comment]
@mycFelix Could u check whether you install heron in a system directory requiring sudo permission? Normally we install heron in user home dir.

**Comment by mycFelix** [comment]
@maosongfu - I did.

The install command is following:
````
sudo ./home/hdfs/heron-install/heron-client-install-0.14.1-centos.sh
````

And the $HERON_HOME is : 
````
[hdfs ~]$ ll /usr/local/heron/
total 28
drwxr-xr-x 2 root root 4096 Jan   1 1970 bin
drwxr-xr-x 6 root root 4096 Jan   1 1970 conf
drwxr-xr-x 2 root root 4096 Jan   1 1970 dist
drwxr-xr-x 2 root root 4096 Jan  19 14:32 etc
drwxr-xr-x 2 root root 4096 Jan   1 1970 examples
drwxr-xr-x 7 root root 4096 Jan   1 1970 lib
-rwxr-xr-x 1 root root  280 Jan   1 1970 release.yaml
````

**Comment by mycFelix** [comment]
@maosongfu - hi

I installed Heron command is following:
````
sudo ./home/hdfs/heron-install/heron-client-install-0.14.1-centos.sh
````
````
[hdfs ~]$ which heron
/usr/local/bin/heron
````
And the $HERON_HOME is : 
````
[hdfs ~]$ ll /usr/local/heron/
total 28
drwxr-xr-x 2 root root 4096 Jan   1 1970 bin
drwxr-xr-x 6 root root 4096 Jan   1 1970 conf
drwxr-xr-x 2 root root 4096 Jan   1 1970 dist
drwxr-xr-x 2 root root 4096 Jan  19 14:32 etc
drwxr-xr-x 2 root root 4096 Jan   1 1970 examples
drwxr-xr-x 7 root root 4096 Jan   1 1970 lib
-rwxr-xr-x 1 root root  280 Jan   1 1970 release.yaml
````
Is this right...?

**Comment by maosongfu** [comment]
You don't need sudo; instead I think you should:
$ ./heron-client-install-VERSION-PLATFORM.sh --user

**Comment by mycFelix** [comment]
I tried,but failed. That's why i write an issue.

I installed Heron using following command on `hdfs` or `miaoyichen` user accont:
````
./home/hdfs/heron-install/heron-client-install-0.14.1-centos.sh --user 
````
I got an error about '/home/.pex' when the topo tried to start heron-shell.

@ashvina told me that it was a problem about the `non admin user accounts` yesterday. But I've followed the guide,but failed too.

**Comment by mycFelix** [comment]
@maosongfu - more details

there is part of logs after i submited a topo:
````
……………………
……………………
[2016-07-19 15:38:43 +0800] org.apache.hadoop.util.NativeCodeLoader Warn:  Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

Powered by
     ___________  ______  ______  _______
    /  ______  / /  ___/ /  ___/ /  ____/
   /     _____/ /  /__  /  /__  /  /___
  /  /\  \     /  ___/ /  ___/ /  ____/
 /  /  \  \   /  /__  /  /__  /  /
/__/    \__\ /_____/ /_____/ /__/

[2016-07-19 15:38:44 +0800] org.apache.reef.util.REEFVersion Info:  REEF Version: 0.14.0
[2016-07-19 15:38:44 +0800] com.twitter.heron.scheduler.yarn.ReefClientSideHandlers Info:  Initializing REEF client handlers for Heron, topology: ExclamationTopology
[2016-07-19 15:38:44 +0800] org.apache.hadoop.yarn.client.RMProxy Info:  Connecting to ResourceManager at CDM1C09-209019061.wdds.com/10.209.19.61:10832
[2016-07-19 15:38:46 +0800] org.apache.reef.runtime.common.files.JobJarMaker Warn:  Failed to delete [/tmp/reef-job-8347081899682646607]
[2016-07-19 15:38:47 +0800] org.apache.reef.runtime.yarn.client.YarnSubmissionHelper Info:  Submitting REEF Application to YARN. ID: application_1468545858776_0024
[2016-07-19 15:38:47 +0800] org.apache.hadoop.yarn.client.api.impl.YarnClientImpl Info:  Submitted application application_1468545858776_0024
[2016-07-19 15:38:50 +0800] com.twitter.heron.scheduler.yarn.ReefClientSideHandlers Info:  Topology ExclamationTopology is running, jobId ExclamationTopology.
[2016-07-19 15:38:50 +0800] com.twitter.heron.statemgr.zookeeper.curator.CuratorStateManager Info:  Closing the CuratorClient to: CDM1C09-209019064.wdds.com:10218
2016-07-19 15:38:50,328 INFO  [main] zookeeper.ZooKeeper (ZooKeeper.java:close(684)) - Session: 0x155dd32e71da634 closed
2016-07-19 15:38:50,328 INFO  [main-EventThread] zookeeper.ClientCnxn (ClientCnxn.java:run(512)) - EventThread shut down
[2016-07-19 15:38:50 +0800] com.twitter.heron.statemgr.zookeeper.curator.CuratorStateManager Info:  Closing the tunnel processes

````
The last log I got is `Closing the tunnel processes`
The program seems to have hung up and wait for some signal to close.  
Is this right?

**Comment by ashvina** [comment]
@mycFelix The Heron client uses REEF client to submit the topology. The REEF library is waiting for some internal events. I am working on that issue with the REEF team. However the wait does not cause topology submission failure. Please ignore that for now.

**Comment by mycFelix** [comment]
@ashvina Thanks you very much. I'll do some other tests on YARN mode.

**Comment by ashvina** [comment]
Hi @mycFelix, I am also looking at the permission denied error. In my test the user submitting the topology was also a user on YARN cluster and existed on all YARN nodes. I do not get the error. Does that work for you?

**Comment by mycFelix** [comment]
Hi @ashvina , I can run mapreduce or spark job on our Yarn cluster using `hdfs` or `miaoyichen` user. 

I tried it again using `hdfs` user. The topo was running correctly and metrics info was showed on UI. I do have the log-files,one of container's log is following:
````
[hdfs@CDM1C10-209019142 log-files]$ tail container_1_exclaim1_1.log.0
[2016-07-20 10:43:08 +0800] stdout STDOUT:  Bolt processed 123700000 tuples in 88031 ms
[2016-07-20 10:43:08 +0800] stdout STDOUT:  Bolt processed 123800000 tuples in 88093 ms
[2016-07-20 10:43:08 +0800] stdout STDOUT:  Bolt processed 123900000 tuples in 88168 ms
[2016-07-20 10:43:08 +0800] stdout STDOUT:  Bolt processed 124000000 tuples in 88245 ms
[2016-07-20 10:43:08 +0800] stdout STDOUT:  Bolt processed 124100000 tuples in 88318 ms
[2016-07-20 10:43:08 +0800] stdout STDOUT:  Bolt processed 124200000 tuples in 88395 ms
[2016-07-20 10:43:08 +0800] stdout STDOUT:  Bolt processed 124300000 tuples in 88471 ms
[2016-07-20 10:43:08 +0800] stdout STDOUT:  Bolt processed 124400000 tuples in 88547 ms
[2016-07-20 10:43:08 +0800] stdout STDOUT:  Bolt processed 124500000 tuples in 88622 ms
[2016-07-20 10:43:08 +0800] stdout STDOUT:  Bolt processed 124600000 tuples in 88685 ms
````
But I failed to open every instance's log&job page,and `all executor terminated` after running a while,maybe tens of minutes, cause the heron-shell didn't  started.

**Comment by ashvina** [comment]
Thanks @mycFelix 
I don't think there is anything wrong with the YARN clusters. This is specific to Heron components on the YARN nodes, https://github.com/twitter/heron/blob/master/website/content/docs/operators/heron-shell.md. 

@maosongfu In case heron-shell is not needed/used, can it be disabled? Or at least temporarily.
Have you noticed the permission error on Aurora clusters?

**Comment by maosongfu** [comment]
@ashvina yes when people tried to install heron in system dir requiring sudo permission, heron will try to do some temp work in HERON_HOME, which is also in system dir requiring sudo permission. May need to think a way to handle it.

**Comment by mycFelix** [comment]
Thank @ashvina and @maosongfu AGAIN!

The situation is I installed Heron using `hdfs` user which is not admin user account following  @maosongfu 's guide. `hdfs` user's $HOME and $HERON_HOME is following:
````
[hdfs@CDM1C10-209019142 ~]$ echo $HOME
/home/hdfs
[hdfs@CDM1C10-209019142 ~]$ echo $HERON_HOME
/home/hdfs/.heron
````

But It seems what Heron-shell finds is `/home/.pex`,following `heron-executor.stdout` logs:
````
pex/common.py", line 103, in safe_mkdir
  File "/usr/lib64/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib64/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib64/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib64/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib64/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/home/.pex'
````

So the Heron-shell failed to start. I think it might be `/home/hdfs/.pex` ?

**Comment by mycFelix** [comment]
@maosongfu - one more basic question.

Do i need to install heron on each node of our cluster using same user account,or just one node to be a client?

**Comment by mycFelix** [comment]
@maosongfu @ashvina  - one more basic question.

Do i need to install heron on each node of our cluster using same user account,or just one node to be a client?

**Comment by ashvina** [comment]
@mycFelix No. Heron client installation is needed on one node only. The client will package the required bits and provide to RM.
