### ISSUE TITLE
Issues when submit topology to remote aurora cluster

### ISSUE THREAD

**Issue by xcf1992** [twitter/heron#1272]
Hi @maosongfu,

I get some strange issues when I submit my topology to the remote aurora cluster, which have only one machine currently.

I have attached some of my config files below. I am guessing I may have some mistakes in these files.

[scheduler.yaml.txt](https://github.com/twitter/heron/files/423382/scheduler.yaml.txt)
[uploader.yaml.txt](https://github.com/twitter/heron/files/423385/uploader.yaml.txt)
[client.yaml.txt](https://github.com/twitter/heron/files/423386/client.yaml.txt)
[heron.aurora.txt](https://github.com/twitter/heron/files/423387/heron.aurora.txt)

The submit message confuses me:
[2016-08-17 11:44:35 -0700] org.apache.curator.utils.DefaultTracerDriver FINEST: Trace: ExistsBuilderImpl-Foreground - 2 ms
[2016-08-17 11:44:35 -0700] com.twitter.heron.scheduler.SubmitterMain SEVERE: Topology already exists

Because I checked the hdfs cluster, there is no such thing under that folder.

Could you take a look at this issue? Thanks.

**Comment by xcf1992** [comment]
›heron submit re/ubuntu/devel --config-path ./heron-conf/ ./target/re-jar-with-dependencies.jar com.h.re.reTopology reTopology --deploy-deactivated --verbose
INFO: Using config file under ./heron-conf/re
DEBUG: {'config_property': [], 'topology-file-name': './target/re-jar-with-dependencies.jar', 'override_config_file': '/var/folders/tm/x0mryh7s14xc0qhljg6yk84m1jfz0t/T/tmp4UQozM/override.yaml', 'config_path': './heron-conf/re', 'subcommand': 'submit', 'deploy_deactivated': 'True', 'cluster': 're', 'topology_main_jvm_property': [], 'role': 'ubuntu', 'environ': 'devel', 'topology-class-name': 'com.h.re.reTopology', 'verbose': 'True'}
DEBUG: $> /Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/bin/java -client -Xmx1g -Dheron.options=cmdline.topologydefn.tmpdirectory=/var/folders/tm/x0mryh7s14xc0qhljg6yk84m1jfz0t/T/tmpMQzjqq,cmdline.topology.initial.state=PAUSED -cp /usr/local/heron/lib/third_party/*:./target/re-jar-with-dependencies.jar com.h.re.reTopology reTopology
11:44:31,899 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
11:44:31,899 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
11:44:31,899 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.xml]
11:44:31,900 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Setting up default configuration.
11:44:32,018 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [com.h.doppler.logback.LogbackDoppler2Appender]
11:44:32,115 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [DOPPLER]
11:44:32,143 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@14:18 - no applicable action for [encoder], current ElementPath  is [[configuration][appender][encoder]]
11:44:32,143 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@15:22 - no applicable action for [pattern], current ElementPath  is [[configuration][appender][encoder][pattern]]
11:44:32,190 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
11:44:32,190 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [CONSOLE]
11:44:32,192 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
11:44:32,197 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
11:44:32,197 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [DOPPLER] to Logger[ROOT]
11:44:32,197 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [CONSOLE] to Logger[ROOT]
11:44:32,197 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
11:44:32,198 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@51cdd8a - Registering current configuration as safe fallback point
[INFO] 2016-08-17 11:44:32.358 |- in com.h.re.reTopology => Topology submitted
INFO: Launching topology 'reTopology'
DEBUG: $> /Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/bin/java -client -Xmx1g -Dheron.options=cmdline.topologydefn.tmpdirectory=/var/folders/tm/x0mryh7s14xc0qhljg6yk84m1jfz0t/T/tmpMQzjqq,cmdline.topology.initial.state=PAUSED -cp /usr/local/heron/lib/scheduler/*:/usr/local/heron/lib/uploader/*:/usr/local/heron/lib/statemgr/*:/usr/local/heron/lib/packing/* com.twitter.heron.scheduler.SubmitterMain --cluster re --role ubuntu --environment devel --heron_home /usr/local/heron --config_path ./heron-conf/re --override_config_file /var/folders/tm/x0mryh7s14xc0qhljg6yk84m1jfz0t/T/tmp4UQozM/override.yaml --release_file /usr/local/heron/release.yaml --topology_package /var/folders/tm/x0mryh7s14xc0qhljg6yk84m1jfz0t/T/tmpMQzjqq/topology.tar.gz --topology_defn /var/folders/tm/x0mryh7s14xc0qhljg6yk84m1jfz0t/T/tmpMQzjqq/reTopology.defn --topology_jar ./target/re-jar-with-dependencies.jar --verbose
[2016-08-17 11:44:34 -0700] com.twitter.heron.common.config.ConfigReader FINE:  Reading config stream
[2016-08-17 11:44:34 -0700] com.twitter.heron.common.config.ConfigReader FINE:  Successfully read config
[2016-08-17 11:44:34 -0700] com.twitter.heron.common.config.ConfigReader FINE:  Reading config stream
[2016-08-17 11:44:34 -0700] com.twitter.heron.common.config.ConfigReader FINE:  Successfully read config
[2016-08-17 11:44:34 -0700] sun.awt.multiscreen.SunDisplayChanger FINEST:  notifyListeners
[2016-08-17 11:44:34 -0700] sun.awt.multiscreen.SunDisplayChanger FINER:  Adding listener: javax.swing.RepaintManager$DisplayChangedHandler@47c62251
[2016-08-17 11:44:34 -0700] com.twitter.heron.common.config.ConfigReader FINE:  Config file ./heron-conf/re/cluster.yaml does not exist
[2016-08-17 11:44:34 -0700] com.twitter.heron.common.config.ConfigReader FINE:  Reading config file ./heron-conf/re/client.yaml
[2016-08-17 11:44:34 -0700] com.twitter.heron.common.config.ConfigReader FINE:  Successfully read config file ./heron-conf/re/client.yaml
[2016-08-17 11:44:34 -0700] com.twitter.heron.common.config.ConfigReader FINE:  Reading config file ./heron-conf/re/packing.yaml
[2016-08-17 11:44:34 -0700] com.twitter.heron.common.config.ConfigReader FINE:  Successfully read config file ./heron-conf/re/packing.yaml
[2016-08-17 11:44:34 -0700] com.twitter.heron.common.config.ConfigReader FINE:  Reading config file ./heron-conf/re/scheduler.yaml
[2016-08-17 11:44:34 -0700] com.twitter.heron.common.config.ConfigReader FINE:  Successfully read config file ./heron-conf/re/scheduler.yaml
[2016-08-17 11:44:34 -0700] com.twitter.heron.common.config.ConfigReader FINE:  Reading config file ./heron-conf/re/statemgr.yaml
[2016-08-17 11:44:34 -0700] com.twitter.heron.common.config.ConfigReader FINE:  Successfully read config file ./heron-conf/re/statemgr.yaml
[2016-08-17 11:44:34 -0700] com.twitter.heron.common.config.ConfigReader FINE:  Reading config file ./heron-conf/re/uploader.yaml
[2016-08-17 11:44:34 -0700] com.twitter.heron.common.config.ConfigReader FINE:  Successfully read config file ./heron-conf/re/uploader.yaml
[2016-08-17 11:44:34 -0700] com.twitter.heron.common.config.ConfigReader FINE:  Reading config file /usr/local/heron/release.yaml
[2016-08-17 11:44:34 -0700] com.twitter.heron.common.config.ConfigReader FINE:  Successfully read config file /usr/local/heron/release.yaml
[2016-08-17 11:44:34 -0700] com.twitter.heron.common.config.ConfigReader FINE:  Reading config file /var/folders/tm/x0mryh7s14xc0qhljg6yk84m1jfz0t/T/tmp4UQozM/override.yaml
[2016-08-17 11:44:34 -0700] com.twitter.heron.common.config.ConfigReader FINE:  Successfully read config file /var/folders/tm/x0mryh7s14xc0qhljg6yk84m1jfz0t/T/tmp4UQozM/override.yaml
[2016-08-17 11:44:34 -0700] com.twitter.heron.scheduler.SubmitterMain FINE:  Static config loaded successfully
[2016-08-17 11:44:34 -0700] com.twitter.heron.scheduler.SubmitterMain FINE:  ("heron.binaries.sandbox.executor", ./heron-core/bin/heron-executor)
("heron.binaries.sandbox.shell", ./heron-core/bin/heron-shell)
("heron.binaries.sandbox.stmgr", ./heron-core/bin/heron-stmgr)
("heron.binaries.sandbox.tmaster", ./heron-core/bin/heron-tmaster)
("heron.build.git.revision", d26a5d932d9562773291863469e586c4f6defa87)
("heron.build.git.status", Clean)
("heron.build.host", tw-mbp-kramasamy)
("heron.build.time", Wed Aug 3 18:16:25 PDT 2016)
("heron.build.timestamp", 1470273420000)
("heron.build.user", kramasamy)
("heron.build.version", 0.14.2)
("heron.class.launcher", com.twitter.heron.scheduler.aurora.AuroraLauncher)
("heron.class.packing.algorithm", com.twitter.heron.packing.roundrobin.RoundRobinPacking)
("heron.class.scheduler", com.twitter.heron.scheduler.aurora.AuroraScheduler)
("heron.class.state.manager", com.twitter.heron.statemgr.zookeeper.curator.CuratorStateManager)
("heron.class.uploader", com.twitter.heron.uploader.hdfs.HdfsUploader)
("heron.classpath.instance", /usr/local/heron/lib/instance/*)
("heron.classpath.metrics.manager", /usr/local/heron/lib/metricsmgr/*)
("heron.classpath.packing", /usr/local/heron/lib/packing/*)
("heron.classpath.sandbox.instance", ./heron-core/lib/instance/*)
("heron.classpath.sandbox.metrics.manager", ./heron-core/lib/metricsmgr/*)
("heron.classpath.sandbox.packing", ./heron-core/lib/packing/*)
("heron.classpath.sandbox.scheduler", ./heron-core/lib/scheduler/*)
("heron.classpath.sandbox.statemgr", ./heron-core/lib/statemgr/*)
("heron.classpath.sandbox.uploader", ./heron-core/lib/uploader/*)
("heron.classpath.scheduler", /usr/local/heron/lib/scheduler/*)
("heron.classpath.statemgr", /usr/local/heron/lib/statemgr/*)
("heron.classpath.uploader", /usr/local/heron/lib/uploader/*)
("heron.config.cluster", re)
("heron.config.environ", devel)
("heron.config.file.client.yaml", ./heron-conf/re/client.yaml)
("heron.config.file.cluster.yaml", ./heron-conf/re/cluster.yaml)
("heron.config.file.defaults.yaml", ./heron-conf/re/defaults.yaml)
("heron.config.file.metrics.yaml", ./heron-conf/re/metrics_sinks.yaml)
("heron.config.file.packing.yaml", ./heron-conf/re/packing.yaml)
("heron.config.file.scheduler.yaml", ./heron-conf/re/scheduler.yaml)
("heron.config.file.statemgr.yaml", ./heron-conf/re/statemgr.yaml)
("heron.config.file.system.yaml", ./heron-conf/re/heron_internals.yaml)
("heron.config.file.uploader.yaml", ./heron-conf/re/uploader.yaml)
("heron.config.role", ubuntu)
("heron.config.sandbox.file.cluster.yaml", ./heron-conf/cluster.yaml)
("heron.config.sandbox.file.defaults.yaml", ./heron-conf/defaults.yaml)
("heron.config.sandbox.file.metrics.yaml", ./heron-conf/metrics_sinks.yaml)
("heron.config.sandbox.file.override.yaml", ./heron-conf/override.yaml)
("heron.config.sandbox.file.packing.yaml", ./heron-conf/packing.yaml)
("heron.config.sandbox.file.scheduler.yaml", ./heron-conf/scheduler.yaml)
("heron.config.sandbox.file.statemgr.yaml", ./heron-conf/statemgr.yaml)
("heron.config.sandbox.file.system.yaml", ./heron-conf/heron_internals.yaml)
("heron.config.sandbox.file.uploader.yaml", ./heron-conf/uploader.yaml)
("heron.config.verbose", true)
("heron.directory.bin", /usr/local/heron/bin)
("heron.directory.conf", ./heron-conf/re)
("heron.directory.dist", /usr/local/heron/dist)
("heron.directory.etc", /usr/local/heron/etc)
("heron.directory.home", /usr/local/heron)
("heron.directory.java.home", /Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home)
("heron.directory.lib", /usr/local/heron/lib)
("heron.directory.sandbox.bin", ./heron-core/bin)
("heron.directory.sandbox.conf", ./heron-conf)
("heron.directory.sandbox.home", ./heron-core)
("heron.directory.sandbox.java.home", /usr/lib/jvm/java-8-openjdk-amd64)
("heron.directory.sandbox.lib", ./heron-core/lib)
("heron.jars.sandbox.scheduler", ./heron-core/lib/scheduler/heron-scheduler.jar)
("heron.jars.scheduler", /usr/local/heron/lib/scheduler/heron-scheduler.jar)
("heron.package.core.uri", hdfs://corehadoop/heron/dist/heron-core-0.14.2-ubuntu.tar.gz)
("heron.package.topology.uri", /heron/topologies/aurora)
("heron.resources.instance.cpu", 1.0)
("heron.resources.instance.disk", 1073741824)
("heron.resources.instance.ram", 1073741824)
("heron.resources.stmgr.ram", 1073741824)
("heron.scheduler.is.service", false)
("heron.statemgr.connection.string", eremesosmaster001:2181)
("heron.statemgr.root.path", /heron)
("heron.statemgr.zookeeper.connection.timeout.ms", 30000)
("heron.statemgr.zookeeper.is.initialize.tree", true)
("heron.statemgr.zookeeper.retry.count", 10)
("heron.statemgr.zookeeper.retry.interval.ms", 10000)
("heron.statemgr.zookeeper.session.timeout.ms", 30000)
("heron.topology.definition.file", /var/folders/tm/x0mryh7s14xc0qhljg6yk84m1jfz0t/T/tmpMQzjqq/reTopology.defn)
("heron.topology.id", reTopology0e4d652c-5a80-46aa-b1e2-dd32ae93033c)
("heron.topology.jar.file", ./target/re-jar-with-dependencies.jar)
("heron.topology.name", reTopology)
("heron.topology.package.file", /var/folders/tm/x0mryh7s14xc0qhljg6yk84m1jfz0t/T/tmpMQzjqq/topology.tar.gz)
("heron.topology.package.type", jar)
("heron.uploader.hdfs.config.directory", ./hdfs-conf)
("heron.uploader.hdfs.topologies.directory.uri", /heron/topologies/aurora)

[2016-08-17 11:44:34 -0700] com.twitter.heron.statemgr.FileSystemStateManager FINE:  File system state manager root address: /heron
[2016-08-17 11:44:34 -0700] com.twitter.heron.statemgr.zookeeper.curator.CuratorStateManager INFO:  Starting client to: eremesosmaster001:2181
[2016-08-17 11:44:34 -0700] org.apache.curator.framework.imps.CuratorFrameworkImpl INFO:  Starting
[2016-08-17 11:44:34 -0700] org.apache.curator.CuratorZookeeperClient FINE:  Starting
[2016-08-17 11:44:34 -0700] org.apache.curator.ConnectionState FINE:  Starting
[2016-08-17 11:44:34 -0700] org.apache.curator.ConnectionState FINE:  reset
[2016-08-17 11:44:34 -0700] org.apache.zookeeper.ZooKeeper INFO:  Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
[2016-08-17 11:44:34 -0700] org.apache.zookeeper.ZooKeeper INFO:  Client environment:host.name=localhost
[2016-08-17 11:44:34 -0700] org.apache.zookeeper.ZooKeeper INFO:  Client environment:java.version=1.8.0_60
[2016-08-17 11:44:34 -0700] org.apache.zookeeper.ZooKeeper INFO:  Client environment:java.vendor=Oracle Corporation
[2016-08-17 11:44:34 -0700] org.apache.zookeeper.ZooKeeper INFO:  Client environment:java.home=/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre
[2016-08-17 11:44:34 -0700] org.apache.zookeeper.ZooKeeper INFO:  Client environment:java.class.path=/usr/local/heron/lib/scheduler/heron-aurora-scheduler.jar:/usr/local/heron/lib/scheduler/heron-binpacking-packing.jar:/usr/local/heron/lib/scheduler/heron-local-scheduler.jar:/usr/local/heron/lib/scheduler/heron-mesos-scheduler.jar:/usr/local/heron/lib/scheduler/heron-roundrobin-packing.jar:/usr/local/heron/lib/scheduler/heron-scheduler.jar:/usr/local/heron/lib/scheduler/heron-slurm-scheduler.jar:/usr/local/heron/lib/scheduler/heron-yarn-scheduler.jar:/usr/local/heron/lib/uploader/heron-hdfs-uploader.jar:/usr/local/heron/lib/uploader/heron-localfs-uploader.jar:/usr/local/heron/lib/uploader/heron-null-uploader.jar:/usr/local/heron/lib/uploader/heron-s3-uploader.jar:/usr/local/heron/lib/uploader/heron-scp-uploader.jar:/usr/local/heron/lib/statemgr/heron-localfs-statemgr.jar:/usr/local/heron/lib/statemgr/heron-zookeeper-statemgr.jar:/usr/local/heron/lib/packing/heron-binpacking-packing.jar:/usr/local/heron/lib/packing/heron-roundrobin-packing.jar
[2016-08-17 11:44:34 -0700] org.apache.zookeeper.ZooKeeper INFO:  Client environment:java.library.path=/Users/cx/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
[2016-08-17 11:44:34 -0700] org.apache.zookeeper.ZooKeeper INFO:  Client environment:java.io.tmpdir=/var/folders/tm/x0mryh7s14xc0qhljg6yk84m1jfz0t/T/
[2016-08-17 11:44:34 -0700] org.apache.zookeeper.ZooKeeper INFO:  Client environment:java.compiler=<NA>
[2016-08-17 11:44:34 -0700] org.apache.zookeeper.ZooKeeper INFO:  Client environment:os.name=Mac OS X
[2016-08-17 11:44:34 -0700] org.apache.zookeeper.ZooKeeper INFO:  Client environment:os.arch=x86_64
[2016-08-17 11:44:34 -0700] org.apache.zookeeper.ZooKeeper INFO:  Client environment:os.version=10.11.6
[2016-08-17 11:44:34 -0700] org.apache.zookeeper.ZooKeeper INFO:  Client environment:user.name=cx
[2016-08-17 11:44:34 -0700] org.apache.zookeeper.ZooKeeper INFO:  Client environment:user.home=/Users/cx
[2016-08-17 11:44:34 -0700] org.apache.zookeeper.ZooKeeper INFO:  Client environment:user.dir=/Users/cx/Work/re
[2016-08-17 11:44:34 -0700] org.apache.zookeeper.ZooKeeper INFO:  Initiating client connection, connectString=eremesosmaster001:2181 sessionTimeout=30000 watcher=org.apache.curator.ConnectionState@7ba18f1b
[2016-08-17 11:44:34 -0700] org.apache.zookeeper.ClientCnxn FINE:  zookeeper.disableAutoWatchReset is false
[2016-08-17 11:44:34 -0700] org.apache.zookeeper.ClientCnxn INFO:  Opening socket connection to server eremesosmaster001.server.h.com/10.128.35.212:2181. Will not attempt to authenticate using SASL (unknown error)
[2016-08-17 11:44:34 -0700] org.apache.zookeeper.ClientCnxn INFO:  Socket connection established to eremesosmaster001.server.h.com/10.128.35.212:2181, initiating session
[2016-08-17 11:44:34 -0700] org.apache.zookeeper.ClientCnxn FINE:  Session establishment request sent on eremesosmaster001.server.h.com/10.128.35.212:2181
[2016-08-17 11:44:34 -0700] org.apache.zookeeper.ClientCnxnSocket FINEST:  readConnectResult 37 0x[0,0,0,0,0,0,75,30,1,56,ffffff90,ffffffb3,ffffffa7,ffffffd6,0,78,0,0,0,10,39,21,ffffff96,6f,12,2,ffffffff,5,12,fffffffe,ffffff9a,70,ffffffa5,ffffff8e,ffffff8a,ffffffda,0,]
[2016-08-17 11:44:34 -0700] org.apache.zookeeper.ClientCnxn INFO:  Session establishment complete on server eremesosmaster001.server.h.com/10.128.35.212:2181, sessionid = 0x15690b3a7d60078, negotiated timeout = 30000
[2016-08-17 11:44:34 -0700] org.apache.curator.framework.state.ConnectionStateManager INFO:  State change: CONNECTED
[2016-08-17 11:44:34 -0700] com.twitter.heron.statemgr.zookeeper.curator.CuratorStateManager INFO:  Topologies directory: /heron/topologies
[2016-08-17 11:44:34 -0700] com.twitter.heron.statemgr.zookeeper.curator.CuratorStateManager INFO:  Tmaster location directory: /heron/tmasters
[2016-08-17 11:44:34 -0700] org.apache.curator.utils.DefaultTracerDriver FINEST:  Trace: connection-state-parent-process - 1 ms
[2016-08-17 11:44:34 -0700] com.twitter.heron.statemgr.zookeeper.curator.CuratorStateManager INFO:  Physical plan directory: /heron/pplans
[2016-08-17 11:44:34 -0700] com.twitter.heron.statemgr.zookeeper.curator.CuratorStateManager INFO:  Execution state directory: /heron/executionstate
[2016-08-17 11:44:34 -0700] com.twitter.heron.statemgr.zookeeper.curator.CuratorStateManager INFO:  Scheduler location directory: /heron/schedulers
[2016-08-17 11:44:35 -0700] org.apache.zookeeper.ClientCnxn FINE:  Reading reply sessionid:0x15690b3a7d60078, packet:: clientPath:null serverPath:null finished:false header:: 1,3  replyHeader:: 1,304,0  request:: '/heron,F  response:: s{274,274,1471385095681,1471385095681,0,5,0,0,0,5,279}
[2016-08-17 11:44:35 -0700] org.apache.zookeeper.ClientCnxn FINE:  Reading reply sessionid:0x15690b3a7d60078, packet:: clientPath:null serverPath:null finished:false header:: 2,3  replyHeader:: 2,304,0  request:: '/heron/topologies,F  response:: s{275,275,1471385095688,1471385095688,0,1,0,0,0,1,280}
[2016-08-17 11:44:35 -0700] org.apache.curator.utils.DefaultTracerDriver FINEST:  Trace: ExistsBuilderImpl-Foreground-CreateParents - 15 ms
[2016-08-17 11:44:35 -0700] org.apache.zookeeper.ClientCnxn FINE:  Reading reply sessionid:0x15690b3a7d60078, packet:: clientPath:null serverPath:null finished:false header:: 3,3  replyHeader:: 3,304,-101  request:: '/heron/topologies/foo,F  response::
[2016-08-17 11:44:35 -0700] org.apache.curator.utils.DefaultTracerDriver FINEST:  Trace: ExistsBuilderImpl-Foreground - 3 ms
[2016-08-17 11:44:35 -0700] org.apache.zookeeper.ClientCnxn FINE:  Reading reply sessionid:0x15690b3a7d60078, packet:: clientPath:null serverPath:null finished:false header:: 4,3  replyHeader:: 4,304,0  request:: '/heron,F  response:: s{274,274,1471385095681,1471385095681,0,5,0,0,0,5,279}
[2016-08-17 11:44:35 -0700] org.apache.zookeeper.ClientCnxn FINE:  Reading reply sessionid:0x15690b3a7d60078, packet:: clientPath:null serverPath:null finished:false header:: 5,3  replyHeader:: 5,304,0  request:: '/heron/tmasters,F  response:: s{276,276,1471385095700,1471385095700,0,0,0,0,0,0,276}
[2016-08-17 11:44:35 -0700] org.apache.curator.utils.DefaultTracerDriver FINEST:  Trace: ExistsBuilderImpl-Foreground-CreateParents - 6 ms
[2016-08-17 11:44:35 -0700] org.apache.zookeeper.ClientCnxn FINE:  Reading reply sessionid:0x15690b3a7d60078, packet:: clientPath:null serverPath:null finished:false header:: 6,3  replyHeader:: 6,304,-101  request:: '/heron/tmasters/foo,F  response::
[2016-08-17 11:44:35 -0700] org.apache.curator.utils.DefaultTracerDriver FINEST:  Trace: ExistsBuilderImpl-Foreground - 3 ms
[2016-08-17 11:44:35 -0700] org.apache.zookeeper.ClientCnxn FINE:  Reading reply sessionid:0x15690b3a7d60078, packet:: clientPath:null serverPath:null finished:false header:: 7,3  replyHeader:: 7,304,0  request:: '/heron,F  response:: s{274,274,1471385095681,1471385095681,0,5,0,0,0,5,279}
[2016-08-17 11:44:35 -0700] org.apache.zookeeper.ClientCnxn FINE:  Reading reply sessionid:0x15690b3a7d60078, packet:: clientPath:null serverPath:null finished:false header:: 8,3  replyHeader:: 8,304,0  request:: '/heron/pplans,F  response:: s{277,277,1471385095710,1471385095710,0,0,0,0,0,0,277}
[2016-08-17 11:44:35 -0700] org.apache.curator.utils.DefaultTracerDriver FINEST:  Trace: ExistsBuilderImpl-Foreground-CreateParents - 5 ms
[2016-08-17 11:44:35 -0700] org.apache.zookeeper.ClientCnxn FINE:  Reading reply sessionid:0x15690b3a7d60078, packet:: clientPath:null serverPath:null finished:false header:: 9,3  replyHeader:: 9,304,-101  request:: '/heron/pplans/foo,F  response::
[2016-08-17 11:44:35 -0700] org.apache.curator.utils.DefaultTracerDriver FINEST:  Trace: ExistsBuilderImpl-Foreground - 2 ms
[2016-08-17 11:44:35 -0700] org.apache.zookeeper.ClientCnxn FINE:  Reading reply sessionid:0x15690b3a7d60078, packet:: clientPath:null serverPath:null finished:false header:: 10,3  replyHeader:: 10,304,0  request:: '/heron,F  response:: s{274,274,1471385095681,1471385095681,0,5,0,0,0,5,279}
[2016-08-17 11:44:35 -0700] org.apache.zookeeper.ClientCnxn FINE:  Reading reply sessionid:0x15690b3a7d60078, packet:: clientPath:null serverPath:null finished:false header:: 11,3  replyHeader:: 11,304,0  request:: '/heron/executionstate,F  response:: s{278,278,1471385095719,1471385095719,0,1,0,0,0,1,281}
[2016-08-17 11:44:35 -0700] org.apache.curator.utils.DefaultTracerDriver FINEST:  Trace: ExistsBuilderImpl-Foreground-CreateParents - 5 ms
[2016-08-17 11:44:35 -0700] org.apache.zookeeper.ClientCnxn FINE:  Reading reply sessionid:0x15690b3a7d60078, packet:: clientPath:null serverPath:null finished:false header:: 12,3  replyHeader:: 12,304,-101  request:: '/heron/executionstate/foo,F  response::
[2016-08-17 11:44:35 -0700] org.apache.curator.utils.DefaultTracerDriver FINEST:  Trace: ExistsBuilderImpl-Foreground - 2 ms
[2016-08-17 11:44:35 -0700] org.apache.zookeeper.ClientCnxn FINE:  Reading reply sessionid:0x15690b3a7d60078, packet:: clientPath:null serverPath:null finished:false header:: 13,3  replyHeader:: 13,304,0  request:: '/heron,F  response:: s{274,274,1471385095681,1471385095681,0,5,0,0,0,5,279}
[2016-08-17 11:44:35 -0700] org.apache.zookeeper.ClientCnxn FINE:  Reading reply sessionid:0x15690b3a7d60078, packet:: clientPath:null serverPath:null finished:false header:: 14,3  replyHeader:: 14,304,0  request:: '/heron/schedulers,F  response:: s{279,279,1471385095728,1471385095728,0,0,0,0,0,0,279}
[2016-08-17 11:44:35 -0700] org.apache.curator.utils.DefaultTracerDriver FINEST:  Trace: ExistsBuilderImpl-Foreground-CreateParents - 5 ms
[2016-08-17 11:44:35 -0700] org.apache.zookeeper.ClientCnxn FINE:  Reading reply sessionid:0x15690b3a7d60078, packet:: clientPath:null serverPath:null finished:false header:: 15,3  replyHeader:: 15,304,-101  request:: '/heron/schedulers/foo,F  response::
[2016-08-17 11:44:35 -0700] org.apache.curator.utils.DefaultTracerDriver FINEST:  Trace: ExistsBuilderImpl-Foreground - 2 ms
[2016-08-17 11:44:35 -0700] com.twitter.heron.statemgr.zookeeper.curator.CuratorStateManager INFO:  Directory tree initialized.
[2016-08-17 11:44:35 -0700] com.twitter.heron.statemgr.zookeeper.curator.CuratorStateManager INFO:  Checking existence of path: /heron/topologies/reTopology
[2016-08-17 11:44:35 -0700] org.apache.zookeeper.ClientCnxn FINE:  Reading reply sessionid:0x15690b3a7d60078, packet:: clientPath:null serverPath:null finished:false header:: 16,3  replyHeader:: 16,304,0  request:: '/heron/topologies/reTopology,F  response:: s{280,280,1471385099944,1471385099944,0,0,0,0,2187,0,280}
[2016-08-17 11:44:35 -0700] org.apache.curator.utils.DefaultTracerDriver FINEST:  Trace: ExistsBuilderImpl-Foreground - 2 ms
[2016-08-17 11:44:35 -0700] com.twitter.heron.scheduler.SubmitterMain SEVERE:  Topology already exists
[2016-08-17 11:44:35 -0700] com.twitter.heron.statemgr.zookeeper.curator.CuratorStateManager INFO:  Closing the CuratorClient to: eremesosmaster001:2181
[2016-08-17 11:44:35 -0700] org.apache.curator.framework.imps.CuratorFrameworkImpl FINE:  Closing
[2016-08-17 11:44:35 -0700] org.apache.curator.CuratorZookeeperClient FINE:  Closing
[2016-08-17 11:44:35 -0700] org.apache.curator.ConnectionState FINE:  Closing
[2016-08-17 11:44:35 -0700] org.apache.zookeeper.ZooKeeper FINE:  Closing session: 0x15690b3a7d60078
[2016-08-17 11:44:35 -0700] org.apache.zookeeper.ClientCnxn FINE:  Closing client for session: 0x15690b3a7d60078
[2016-08-17 11:44:35 -0700] org.apache.zookeeper.ClientCnxn FINE:  Reading reply sessionid:0x15690b3a7d60078, packet:: clientPath:null serverPath:null finished:false header:: 17,-11  replyHeader:: 17,305,0  request:: null response:: null
[2016-08-17 11:44:35 -0700] org.apache.zookeeper.ClientCnxn FINE:  Disconnecting client for session: 0x15690b3a7d60078
[2016-08-17 11:44:35 -0700] org.apache.zookeeper.ZooKeeper INFO:  Session: 0x15690b3a7d60078 closed
[2016-08-17 11:44:35 -0700] org.apache.zookeeper.ClientCnxn INFO:  EventThread shut down
[2016-08-17 11:44:35 -0700] com.twitter.heron.statemgr.zookeeper.curator.CuratorStateManager INFO:  Closing the tunnel processes
Exception in thread "main" java.lang.RuntimeException: Failed to submit topology reTopology
	at com.twitter.heron.scheduler.SubmitterMain.main(SubmitterMain.java:319)
[2016-08-17 11:44:35 -0700] org.apache.zookeeper.ClientCnxnSocketNIO FINEST:  Doing client selector close
[2016-08-17 11:44:35 -0700] org.apache.zookeeper.ClientCnxnSocketNIO FINEST:  Closed client selector
[2016-08-17 11:44:35 -0700] org.apache.zookeeper.ClientCnxn FINEST:  SendThread exitedloop.
ERROR: Failed to launch topology 'reTopology' because User main failed with status 1. Bailing out...
Traceback (most recent call last):
  File "heron/cli/src/python/submit.py", line 145, in launch_topologies
    launch_a_topology(cl_args, tmp_dir, topology_file, defn_file)
  File "heron/cli/src/python/submit.py", line 110, in launch_a_topology
    java_defines=[]
  File "heron/cli/src/python/execute.py", line 68, in heron_class
    raise RuntimeError(err_str)
RuntimeError: User main failed with status 1. Bailing out...
INFO: Elapsed time: 6.896s.

**Comment by billonahill** [comment]
See this line in your logs:
```
[2016-08-17 11:44:35 -0700] com.twitter.heron.scheduler.SubmitterMain SEVERE: Topology already exists
```

Kill the topology in aurora and then try to submit.

**Comment by billonahill** [comment]
Also, please use the email forums for troubleshooting issues instead of creating github issues.
