### ISSUE TITLE
Error while submitting topology: instancePlan.hashCode method not found

### ISSUE THREAD

**Issue by ashvina** [twitter/heron#1351]
```
Exception in thread "main" java.lang.NoSuchMethodError: java.lang.Long.hashCode(J)I
        at com.twitter.heron.spi.packing.Resource.hashCode(Resource.java:57)
        at com.twitter.heron.spi.packing.PackingPlan$InstancePlan.hashCode(PackingPlan.java:209)
        at java.util.HashMap.hash(HashMap.java:362)
        at java.util.HashMap.put(HashMap.java:492)
        at java.util.HashSet.add(HashSet.java:217)
        at java.util.AbstractCollection.addAll(AbstractCollection.java:342)
        at java.util.HashSet.<init>(HashSet.java:117)
        at com.twitter.heron.packing.roundrobin.RoundRobinPacking.pack(RoundRobinPacking.java:146)
        at com.twitter.heron.spi.utils.LauncherUtils.createPackingPlan(LauncherUtils.java:62)
        at com.twitter.heron.scheduler.LaunchRunner.call(LaunchRunner.java:123)
        at com.twitter.heron.scheduler.SubmitterMain.callLauncherRunner(SubmitterMain.java:459)
        at com.twitter.heron.scheduler.SubmitterMain.submitTopology(SubmitterMain.java:413)
        at com.twitter.heron.scheduler.SubmitterMain.main(SubmitterMain.java:322)
ERROR: Failed to launch topology 'ExclamationTopology' because User main failed with status 1. Bailing out...
```
heron.build.git.revision : 3890bc08b213dcddc82f9672a6d467c8e06777f9

**Comment by billonahill** [comment]
`java.lang.Long.hashCode` was removed in Java 8.

**Comment by billonahill** [comment]
Hmm, I still see it in java 8 actually.

**Comment by ashvina** [comment]
Interesting... is it the other way around? I am trying this on Java 7

**Comment by billonahill** [comment]
Yes, it is. It's `Long.hashCode(long value)` which was introduced in 1.8. We should change it to `longValue.hashCode()` which is 1.7 compliant.
