### ISSUE TITLE
Failed to close heron-tracker in multi statemgrs config

### ISSUE THREAD

**Issue by mycFelix** [twitter/heron#1379]
Hi,

I'm using Heron 0.14.3.

The ` .herontools/conf/heron_tracker.yaml` is following:
````
statemgrs:
  -
    type: "file"
    name: "local"
    rootpath: "~/.herondata/repository/state/local"
    tunnelhost: "localhost"
  -
    type: "zookeeper"
    name: "yarn"
    hostport: "CDM1C09-209019064.wdds.com:10218"
    rootpath: "/heron"
    tunnelhost: "localhost"
````

There is an error once I close `heron-tracker` using `cmd+c` .
````
NFO: 09/13/2016 10:57:53 +0000 Sending request(xid=9): Close()
INFO: 09/13/2016 10:57:53 +0000 Closing connection to cdm1c09-209019064.wdds.com:10218
INFO: 09/13/2016 10:57:53 +0000 Zookeeper session lost, state: CLOSED
INFO: 09/13/2016 10:57:53 +0000 Connection state changed to: LOST
Traceback (most recent call last):
  File "/home/hdfs/bin/heron-tracker/.bootstrap/_pex/pex.py", line 328, in execute
  File "/home/hdfs/bin/heron-tracker/.bootstrap/_pex/pex.py", line 260, in _wrap_coverage
  File "/home/hdfs/bin/heron-tracker/.bootstrap/_pex/pex.py", line 292, in _wrap_profiling
  File "/home/hdfs/bin/heron-tracker/.bootstrap/_pex/pex.py", line 371, in _execute
  File "/home/hdfs/bin/heron-tracker/.bootstrap/_pex/pex.py", line 429, in execute_entry
  File "/home/hdfs/bin/heron-tracker/.bootstrap/_pex/pex.py", line 434, in execute_module
  File "/usr/lib64/python2.7/runpy.py", line 180, in run_module
    fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/hdfs/bin/heron-tracker/heron/tools/tracker/src/python/main.py", line 231, in <module>
  File "/home/hdfs/bin/heron-tracker/heron/tools/tracker/src/python/main.py", line 228, in main
  File "/home/hdfs/.pex/install/tornado-4.0.2-py2.7-linux-x86_64.egg.581734a0fde152f02c20ce1e54f3d93a7725a09f/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/ioloop.py", line 812, in start
    event_pairs = self._impl.poll(poll_timeout)
  File "/home/hdfs/bin/heron-tracker/heron/tools/tracker/src/python/main.py", line 215, in signal_handler
  File "/home/hdfs/bin/heron-tracker/heron/tools/tracker/src/python/main.py", line 81, in stop
  File "/home/hdfs/bin/heron-tracker/heron/tools/tracker/src/python/tracker.py", line 84, in stop_sync
  File "/home/hdfs/bin/heron-tracker/heron/statemgrs/src/python/zkstatemanager.py", line 65, in stop
  File "/home/hdfs/bin/heron-tracker/heron/statemgrs/src/python/statemanager.py", line 125, in terminate_ssh_tunnel
AttributeError: 'ZkStateManager' object has no attribute 'tunnel'
^C
````

There are two affects：
1.  heron-tracker is failed to close
2. The `cli` seems hang up . The only way to kill `heron-tracker` is `kill -9 <pid>`

**Comment by objmagic** [comment]
May I know which version of Heron you were using?
