### ISSUE TITLE
NetworkUtilsTest.testGetInetSocketAddress when can get host1 ip

### ISSUE THREAD

**Issue by mtunique** [twitter/heron#1384]
NetworkUtilsTest.testGetInetSocketAddress when can get host1 ip.

Test log:

There was 1 failure:
1) testGetInetSocketAddress(com.twitter.heron.spi.utils.NetworkUtilsTest)
org.junit.ComparisonFailure: expected:<host[]:999> but was:<host[/10.1.0.47]:999>
       	at org.junit.Assert.assertEquals(Assert.java:115)
       	at org.junit.Assert.assertEquals(Assert.java:144)
       	at com.twitter.heron.spi.utils.NetworkUtilsTest.testGetInetSocketAddress(NetworkUtilsTest.java:275)
       	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
       	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       	at java.lang.reflect.Method.invoke(Method.java:498)
       	at org.junit.internal.runners.TestMethod.invoke(TestMethod.java:68)
       	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:310)
       	at org.junit.internal.runners.MethodRoadie$2.run(MethodRoadie.java:88)
       	at org.junit.internal.runners.MethodRoadie.runBeforesThenTestThenAfters(MethodRoadie.java:96)
       	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.executeTest(PowerMockJUnit44RunnerDelegateImpl.java:294)
       	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTestInSuper(PowerMockJUnit47RunnerDelegateImpl.java:127)
       	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTest(PowerMockJUnit47RunnerDelegateImpl.java:82)
       	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runBeforesThenTestThenAfters(PowerMockJUnit44RunnerDelegateImpl.java:282)
       	at org.junit.internal.runners.MethodRoadie.runTest(MethodRoadie.java:86)
       	at org.junit.internal.runners.MethodRoadie.run(MethodRoadie.java:49)
       	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.invokeTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:207)
       	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.runMethods(PowerMockJUnit44RunnerDelegateImpl.java:146)
       	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$1.run(PowerMockJUnit44RunnerDelegateImpl.java:120)
       	at org.junit.internal.runners.ClassRoadie.runUnprotected(ClassRoadie.java:33)
       	at org.junit.internal.runners.ClassRoadie.runProtected(ClassRoadie.java:45)
       	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.run(PowerMockJUnit44RunnerDelegateImpl.java:122)
       	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.run(JUnit4TestSuiteChunkerImpl.java:106)
       	at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.run(AbstractCommonPowerMockRunner.java:53)
       	at org.powermock.modules.junit4.PowerMockRunner.run(PowerMockRunner.java:59)
       	at com.google.testing.junit.runner.junit4.CancellableRequestFactory$CancellableRunner.run(CancellableRequestFactory.java:89)
       	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
       	at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
       	at com.google.testing.junit.runner.junit4.JUnit4Runner.run(JUnit4Runner.java:114)
       	at com.google.testing.junit.runner.BazelTestRunner.runTestsInSuite(BazelTestRunner.java:152)
       	at com.google.testing.junit.runner.BazelTestRunner.main(BazelTestRunner.java:91)

**Comment by mtunique** [comment]
Because of the same reason, TMasterSinkTest.testTMasterClientService is also failed.
