### ISSUE TITLE
Erroneous MM response (PyHeron)

### ISSUE THREAD

**Issue by objmagic** [twitter/heron#1479]
```
10/06/2016 14:45:55 -0700:INFO:spout_instance.py: Adding spout task...
10/06/2016 14:45:55 -0700:INFO:st_heron_instance.py: Started instance successfully.
10/06/2016 14:46:00 -0700:ERROR:event_looper.py: Error occured during _run_once(): Response from Metrics Manager not OK
10/06/2016 14:46:00 -0700:ERROR:event_looper.py: Traceback (most recent call last):
  File "heron/common/src/python/basics/event_looper.py", line 65, in _run_once
    self._trigger_timers()
  File "heron/common/src/python/basics/event_looper.py", line 146, in _trigger_timers
    task()
  File "heron/common/src/python/network/heron_client.py", line 213, in timeout_task
    self.handle_timeout(reqid)
  File "heron/common/src/python/network/heron_client.py", line 230, in handle_timeout
    self.on_response(StatusCode.TIMEOUT_ERROR, context, None)
  File "heron/instance/src/python/network/metricsmgr_client.py", line 80, in on_response
    raise RuntimeError("Response from Metrics Manager not OK")
RuntimeError: Response from Metrics Manager not OK
```

**Comment by maosongfu** [comment]
Can you also check metrics-mgr's log?

**Comment by objmagic** [comment]
turns out I found some err log in Stream Manager's log. They look helpful

```
E1006 14:35:00.763510 2053763072 server.cpp:170] Unknown type protobuf received heron.proto.stmgr.TupleMessage deleting...
E1006 14:35:01.130671 2053763072 server.cpp:170] Unknown type protobuf received heron.proto.stmgr.TupleMessage deleting...
E1006 14:35:01.138960 2053763072 server.cpp:170] Unknown type protobuf received heron.proto.stmgr.TupleMessage deleting...
E1006 14:35:01.462795 2053763072 server.cpp:170] Unknown type protobuf received heron.proto.stmgr.TupleMessage deleting...
E1006 14:35:01.472683 2053763072 server.cpp:170] Unknown type protobuf received heron.proto.stmgr.TupleMessage deleting...
E1006 14:35:01.787544 2053763072 server.cpp:170] Unknown type protobuf received heron.proto.stmgr.TupleMessage deleting...
E1006 14:35:01.794572 2053763072 server.cpp:170] Unknown type protobuf received heron.proto.stmgr.TupleMessage deleting...
E1006 14:35:02.104367 2053763072 server.cpp:170] Unknown type protobuf received heron.proto.stmgr.TupleMessage deleting...
E1006 14:35:02.141191 2053763072 server.cpp:170] Unknown type protobuf received heron.proto.stmgr.TupleMessage deleting...
E1006 14:35:02.480409 2053763072 server.cpp:170] Unknown type protobuf received heron.proto.stmgr.TupleMessage deleting...
E1006 14:35:02.538857 2053763072 server.cpp:170] Unknown type protobuf received heron.proto.stmgr.TupleMessage deleting...
E1006 14:35:02.832093 2053763072 server.cpp:170] Unknown type protobuf received heron.proto.stmgr.TupleMessage deleting...
E1006 14:35:02.881032 2053763072 server.cpp:170] Unknown type protobuf received heron.proto.stmgr.TupleMessage deleting...
E1006 14:35:03.150892 2053763072 server.cpp:170] Unknown type protobuf received heron.proto.stmgr.TupleMessage deleting...
E1006 14:35:03.190521 2053763072 server.cpp:170] Unknown type protobuf received heron.proto.stmgr.TupleMessage deleting...
E1006 14:35:03.463342 2053763072 server.cpp:170] Unknown type protobuf received heron.proto.stmgr.TupleMessage deleting...
E1006 14:35:03.569996 2053763072 server.cpp:170] Unknown type protobuf received heron.proto.stmgr.TupleMessage deleting...
E1006 14:35:03.850342 2053763072 server.cpp:170] Unknown type protobuf received heron.proto.stmgr.TupleMessage deleting...
E1006 14:35:03.899875 2053763072 server.cpp:170] Unknown type protobuf received heron.proto.stmgr.TupleMessage deleting...
E1006 14:35:04.181701 2053763072 server.cpp:170] Unknown type protobuf received heron.proto.stmgr.TupleMessage deleting...
E1006 14:35:04.209309 2053763072 server.cpp:170] Unknown type protobuf received heron.proto.stmgr.TupleMessage deleting...
E1006 14:35:04.481101 2053763072 server.cpp:170] Unknown type protobuf received heron.proto.stmgr.TupleMessage deleting...
E1006 14:35:04.506788 2053763072 server.cpp:170] Unknown type protobuf received heron.proto.stmgr.TupleMessage deleting...
E1006 14:35:04.778338 2053763072 server.cpp:170] Unknown type protobuf received heron.proto.stmgr.TupleMessage deleting...
E1006 14:35:04.847791 2053763072 server.cpp:170] Unknown type protobuf received heron.proto.stmgr.TupleMessage deleting...
E1006 14:35:05.069424 2053763072 server.cpp:170] Unknown type protobuf received heron.proto.stmgr.TupleMessage deleting...
E1006 14:35:05.244091 2053763072 server.cpp:170] Unknown type protobuf received heron.proto.stmgr.TupleMessage deleting...
E1006 14:35:05.372455 2053763072 server.cpp:170] Unknown type protobuf received heron.proto.stmgr.TupleMessage deleting...
E1006 14:35:05.566292 2053763072 server.cpp:170] Unknown type protobuf received heron.proto.stmgr.TupleMessage deleting...
E1006 14:35:05.765307 2053763072 server.cpp:170] Unknown type protobuf received heron.proto.stmgr.TupleMessage deleting...
E1006 14:35:05.866123 2053763072 server.cpp:170] Unknown type protobuf received heron.proto.stmgr.TupleMessage deleting...
E1006 14:35:06.113798 2053763072 server.cpp:170] Unknown type protobuf received heron.proto.stmgr.TupleMessage deleting...
E1006 14:35:06.168926 2053763072 server.cpp:170] Unknown type protobuf received heron.proto.stmgr.TupleMessage deleting...
```

**Comment by taishi8117** [comment]
I might be wrong but I remember this happened occasionally for Java instances too when Metrics Manager was not yet initialized when the instance sends a request for the first time.

**Comment by objmagic** [comment]
I see. It indeed happens occasionally and the above StmGr err msg is not relevant (I didn't build the core properly...)

**Comment by maosongfu** [comment]
Any updates on this issue?

**Comment by objmagic** [comment]
@maosongfu agree with Taishi's comment. This should be a MM design issue. will look into this.

**Comment by maosongfu** [comment]
Is the metrics-mgr's log still exist or deleted?

It is a bit different from the case @taishi8117  mentioned: java instance could get the exception "connection refused" when Metrics Manager was not yet initialized; but here we received a NOT_OK response.

**Comment by objmagic** [comment]
Java and Python code handle NOT_OK in exact same way:

Java: https://github.com/twitter/heron/blob/master/heron/instance/src/java/com/twitter/heron/network/MetricsManagerClient.java#L177

Python:
https://github.com/twitter/heron/blob/master/heron/instance/src/python/network/metricsmgr_client.py#L80

**Comment by maosongfu** [comment]
Yes they are handling in the same way. 

But this **rarely happens** in java instances. Is there a way to get the log to figure out what happened?

**Comment by objmagic** [comment]
will do.
