### ISSUE TITLE
storm-hdfs (+ other storm-externals) not compatible

### ISSUE THREAD

**Issue by otter-in-a-suit** [twitter/heron#1497]
When trying to use storm-hdfs (1.0.2) with Heron 0.14.3, the storm-internal classes from storm-core (e.g. org/apache/storm/utils/TupleUtils) are not found, resulting in a ClassNotFoundException:

`Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/storm/utils/TupleUtils
	at org.apache.storm.hdfs.bolt.AbstractHdfsBolt.getComponentConfiguration(AbstractHdfsBolt.java:219)
	at org.apache.storm.topology.IRichBoltDelegate.getComponentConfiguration(IRichBoltDelegate.java:70)
	at com.twitter.heron.api.topology.BaseComponentDeclarer.<init>(BaseComponentDeclarer.java:35)
	at com.twitter.heron.api.topology.BoltDeclarer.<init>(BoltDeclarer.java:34)
	at com.twitter.heron.api.topology.TopologyBuilder.setBolt(TopologyBuilder.java:118)
	at org.apache.storm.topology.TopologyBuilder.setBolt(TopologyBuilder.java:44)
	at com.otterinasuit.twitter.Main.main(Main.java:89)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.ClassNotFoundException: org.apache.storm.utils.TupleUtils
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 12 more`

storm-hdfs is invoked as such:

    <dependency>
            <groupId>org.apache.storm</groupId>
            <artifactId>storm-hdfs</artifactId>
            <version>1.0.2</version>
            <exclusions>
                <exclusion>
                    <groupId>org.apache.storm</groupId>
                    <artifactId>storm-core</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

The exclude node is optional / has no apparent effect. Tested on Mac OS 10.2, both by submitting a job and in an IDE.

**Comment by kramasamy** [comment]
@nlu90 - can you take a quick look at this?

**Comment by nlu90** [comment]
@kramasamy Our storm api doesn't have TupleUtils class. We can add one if we want to make the storm-hdfs works without any change.

**Comment by kramasamy** [comment]
Let us add it - we need to support both pre-1.0 and post 1.0 versions, if that is supported in both.

**Comment by nlu90** [comment]
@kramasamy I didn't find the TupleUtils class in storm's 0.9.6 and 0.9.7 source code. I'll assume this class is only added for newer 1.0.x storm.

**Comment by nlu90** [comment]
@otter-in-a-suit we have merged the fix for this issue. Can you test it out with the current master or with the 0.14.5 release?
