### ISSUE TITLE
Heron Scaling

### ISSUE THREAD

**Issue by antoninoxs** [twitter/heron#1508]
Hello I am Antonino and for my thesis in computer engineering I have to work on heron.
I was trying the new update functionality of the parallelism of the operators (Bolt and spout).
If I run it on local cluster everything works and the plan is properly updated. By performing the same operation on Aurora scheduler reflected the following problem:

command:
heron update devcluster/tidus/devel ExclamationTopology --component-parallelism word:2 

result log:
INFO: Using config file under /home/tidus/.heron/conf/devcluster
[2016-10-21 19:50:45 +0200] com.twitter.heron.statemgr.zookeeper.curator.CuratorStateManager INFORMAZIONI:  Starting client to: 192.168.1.16:2181  
[2016-10-21 19:50:45 +0200] org.apache.curator.framework.imps.CuratorFrameworkImpl INFORMAZIONI:  Starting  
[2016-10-21 19:50:45 +0200] org.apache.zookeeper.ZooKeeper INFORMAZIONI:  Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT  
[2016-10-21 19:50:45 +0200] org.apache.zookeeper.ZooKeeper INFORMAZIONI:  Client environment:host.name=VAIO  
[2016-10-21 19:50:45 +0200] org.apache.zookeeper.ZooKeeper INFORMAZIONI:  Client environment:java.version=1.8.0_91  
[2016-10-21 19:50:45 +0200] org.apache.zookeeper.ZooKeeper INFORMAZIONI:  Client environment:java.vendor=Oracle Corporation  
[2016-10-21 19:50:45 +0200] org.apache.zookeeper.ZooKeeper INFORMAZIONI:  Client environment:java.home=/usr/lib/jvm/java-8-openjdk-amd64/jre  
[2016-10-21 19:50:45 +0200] org.apache.zookeeper.ZooKeeper INFORMAZIONI:  Client environment:java.class.path=/home/tidus/.heron/lib/scheduler/heron-roundrobin-packing.jar:/home/tidus/.heron/lib/scheduler/heron-local-scheduler.jar:/home/tidus/.heron/lib/scheduler/heron-aurora-scheduler.jar:/home/tidus/.heron/lib/scheduler/heron-scheduler.jar:/home/tidus/.heron/lib/scheduler/heron-mesos-scheduler.jar:/home/tidus/.heron/lib/scheduler/heron-marathon-scheduler.jar:/home/tidus/.heron/lib/scheduler/heron-binpacking-packing.jar:/home/tidus/.heron/lib/scheduler/heron-yarn-scheduler.jar:/home/tidus/.heron/lib/scheduler/heron-slurm-scheduler.jar:/home/tidus/.heron/lib/statemgr/heron-localfs-statemgr.jar:/home/tidus/.heron/lib/statemgr/heron-zookeeper-statemgr.jar  
[2016-10-21 19:50:45 +0200] org.apache.zookeeper.ZooKeeper INFORMAZIONI:  Client environment:java.library.path=/usr/java/packages/lib/amd64:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib  
[2016-10-21 19:50:45 +0200] org.apache.zookeeper.ZooKeeper INFORMAZIONI:  Client environment:java.io.tmpdir=/tmp  
[2016-10-21 19:50:45 +0200] org.apache.zookeeper.ZooKeeper INFORMAZIONI:  Client environment:java.compiler=<NA>  
[2016-10-21 19:50:45 +0200] org.apache.zookeeper.ZooKeeper INFORMAZIONI:  Client environment:os.name=Linux  
[2016-10-21 19:50:45 +0200] org.apache.zookeeper.ZooKeeper INFORMAZIONI:  Client environment:os.arch=amd64  
[2016-10-21 19:50:45 +0200] org.apache.zookeeper.ZooKeeper INFORMAZIONI:  Client environment:os.version=4.4.0-45-generic  
[2016-10-21 19:50:45 +0200] org.apache.zookeeper.ZooKeeper INFORMAZIONI:  Client environment:user.name=tidus  
[2016-10-21 19:50:45 +0200] org.apache.zookeeper.ZooKeeper INFORMAZIONI:  Client environment:user.home=/home/tidus  
[2016-10-21 19:50:45 +0200] org.apache.zookeeper.ZooKeeper INFORMAZIONI:  Client environment:user.dir=/home/tidus  
[2016-10-21 19:50:45 +0200] org.apache.zookeeper.ZooKeeper INFORMAZIONI:  Initiating client connection, connectString=192.168.1.16:2181 sessionTimeout=30000 watcher=org.apache.curator.ConnectionState@1fc2b765  
[2016-10-21 19:50:45 +0200] org.apache.zookeeper.ClientCnxn INFORMAZIONI:  Opening socket connection to server 192.168.1.16/192.168.1.16:2181. Will not attempt to authenticate using SASL (unknown error)  
[2016-10-21 19:50:45 +0200] org.apache.zookeeper.ClientCnxn INFORMAZIONI:  Socket connection established to 192.168.1.16/192.168.1.16:2181, initiating session  
[2016-10-21 19:50:45 +0200] org.apache.zookeeper.ClientCnxn INFORMAZIONI:  Session establishment complete on server 192.168.1.16/192.168.1.16:2181, sessionid = 0x157e80138720011, negotiated timeout = 30000  
[2016-10-21 19:50:45 +0200] org.apache.curator.framework.state.ConnectionStateManager INFORMAZIONI:  State change: CONNECTED  
[2016-10-21 19:50:45 +0200] com.twitter.heron.statemgr.zookeeper.curator.CuratorStateManager INFORMAZIONI:  TMaster location directory: /heronroot/tmasters  
[2016-10-21 19:50:45 +0200] com.twitter.heron.statemgr.zookeeper.curator.CuratorStateManager INFORMAZIONI:  Topologies directory: /heronroot/topologies  
[2016-10-21 19:50:45 +0200] com.twitter.heron.statemgr.zookeeper.curator.CuratorStateManager INFORMAZIONI:  Packing plan directory: /heronroot/packingplans  
[2016-10-21 19:50:45 +0200] com.twitter.heron.statemgr.zookeeper.curator.CuratorStateManager INFORMAZIONI:  Physical plan directory: /heronroot/pplans  
[2016-10-21 19:50:45 +0200] com.twitter.heron.statemgr.zookeeper.curator.CuratorStateManager INFORMAZIONI:  Execution state directory: /heronroot/executionstate  
[2016-10-21 19:50:45 +0200] com.twitter.heron.statemgr.zookeeper.curator.CuratorStateManager INFORMAZIONI:  Scheduler location directory: /heronroot/schedulers  
[2016-10-21 19:50:45 +0200] com.twitter.heron.statemgr.zookeeper.curator.CuratorStateManager INFORMAZIONI:  Distributed locks directory: /heronroot/locks  
[2016-10-21 19:50:45 +0200] com.twitter.heron.statemgr.zookeeper.curator.CuratorStateManager INFORMAZIONI:  Directory tree initialized.  
[2016-10-21 19:50:45 +0200] com.twitter.heron.statemgr.zookeeper.curator.CuratorStateManager INFORMAZIONI:  Checking existence of path: /heronroot/topologies/ExclamationTopology  
[2016-10-21 19:50:46 +0200] com.twitter.heron.statemgr.zookeeper.curator.CuratorStateManager INFORMAZIONI:  Closing the CuratorClient to: 192.168.1.16:2181  
[2016-10-21 19:50:46 +0200] org.apache.zookeeper.ZooKeeper INFORMAZIONI:  Session: 0x157e80138720011 closed  
[2016-10-21 19:50:46 +0200] com.twitter.heron.statemgr.zookeeper.curator.CuratorStateManager INFORMAZIONI:  Closing the tunnel processes  
Exception in thread "main" java.lang.NullPointerException
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:307)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at com.twitter.heron.spi.utils.ReflectionUtils.newInstance(ReflectionUtils.java:31)
    at com.twitter.heron.spi.utils.ReflectionUtils.newInstance(ReflectionUtils.java:25)
    at com.twitter.heron.scheduler.RuntimeManagerRunner.buildNewPackingPlan(RuntimeManagerRunner.java:277)
    at com.twitter.heron.scheduler.RuntimeManagerRunner.updateTopologyHandler(RuntimeManagerRunner.java:188)
    at com.twitter.heron.scheduler.RuntimeManagerRunner.call(RuntimeManagerRunner.java:80)
    at com.twitter.heron.scheduler.RuntimeManagerMain.callRuntimeManagerRunner(RuntimeManagerMain.java:383)
    at com.twitter.heron.scheduler.RuntimeManagerMain.manageTopology(RuntimeManagerMain.java:341)
    at com.twitter.heron.scheduler.RuntimeManagerMain.main(RuntimeManagerMain.java:266)
[2016-10-21 19:50:46 +0200] org.apache.zookeeper.ClientCnxn INFORMAZIONI:  EventThread shut down  
ERROR: Failed to update topology 'ExclamationTopology': Traceback (most recent call last):
  File "heron/tools/cli/src/python/update.py", line 89, in run
    args=new_args
  File "heron/tools/cli/src/python/execute.py", line 73, in heron_class
    raise RuntimeError(err_str)
RuntimeError: User main failed with status 1. Bailing out...

I using Packing algorithm: binpacking.

where am I wrong?
thanks in advance

**Comment by antoninoxs** [comment]
Sorry i am a newbie

Il 21/Ott/2016 20:21, "Bill Graham" <notifications@github.com> ha scritto:
