### ISSUE TITLE
Improve error message when pom.xml specifying wrong heron-api version

### ISSUE THREAD

**Issue by objmagic** [twitter/heron#1661]
During some internal experiment, we realized that if `pom.xml` specifies a heron-api of version that is different from the version of heron client/heron core that are going to be used, error message is not really helpful:

````
DEBUG: $> /usr/lib/jvm/java-1.8.0-twitter/bin/java -client -Xmx1g -Dheron.options=cmdline.topologydefn.tmpdirectory=/tmp/tmpghL9AU,cmdline.topology.initial.state=RUNNING -cp /home/c/.heron/lib/third_party/*:/home/c/a.jar topologyMain
Exception in thread "main" java.lang.RuntimeException: topology definition temp directory not specified
    at com.twitter.heron.api.HeronSubmitter.submitTopology(HeronSubmitter.java:76)
    at backtype.storm.StormSubmitter.submitTopology(StormSubmitter.java:60)
    at io.fabric.heron.TopologyMain.main(TopologyMain.java:46)
````

Possibly related to https://github.com/twitter/heron/issues/954

**Comment by objmagic** [comment]
this issue definitely has a very low priority, but I created it just to track the problem.
