### ISSUE TITLE
KafkaSpout: java.nio.HeapByteBuffer is not serealizible for emission

### ISSUE THREAD

**Issue by smirnp** [twitter/heron#1795]
The trouble is that KafkaSpout cannot serialize and emit java.nio.HeapByteBuffer, which was readed from Kafka via RawMultiScheme mode. 

My spout:

SpoutConfig spoutConfig = new SpoutConfig(hosts, kafkaTopic, "/" + kafkaTopic, UUID.randomUUID().toString());
spoutConfig.zkServers = Arrays.asList(new String[]{ zkServerHost });
spoutConfig.zkPort = 2181;
spoutConfig.scheme = new RawMultiScheme();
spoutConfig.startOffsetTime = kafka.api.OffsetRequest.EarliestTime();

Error trace:

SEVERE: Exception caught in thread: spout_spout_1 with id: 22
java.lang.IllegalArgumentException: Class is not registered: java.nio.HeapByteBuffer
Note: To register this class use: kryo.register(java.nio.HeapByteBuffer.class);
	at com.esotericsoftware.kryo.Kryo.getRegistration(Kryo.java:488)
	at com.esotericsoftware.kryo.util.DefaultClassResolver.writeClass(DefaultClassResolver.java:97)
	at com.esotericsoftware.kryo.Kryo.writeClass(Kryo.java:517)
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:622)
	at org.apache.storm.serialization.HeronPluggableSerializerDelegate.serialize(HeronPluggableSerializerDelegate.java:47)
	at com.twitter.heron.instance.spout.SpoutOutputCollectorImpl.admitSpoutTuple(SpoutOutputCollectorImpl.java:241)
	at com.twitter.heron.instance.spout.SpoutOutputCollectorImpl.emit(SpoutOutputCollectorImpl.java:117)
	at com.twitter.heron.api.spout.SpoutOutputCollector.emit(SpoutOutputCollector.java:49)
	at org.apache.storm.spout.SpoutOutputCollectorImpl.emit(SpoutOutputCollectorImpl.java:43)
	at org.apache.storm.spout.SpoutOutputCollectorImpl.emit(SpoutOutputCollectorImpl.java:48)
	at org.apache.storm.kafka.PartitionManager.next(PartitionManager.java:171)
	at org.apache.storm.kafka.KafkaSpout.nextTuple(KafkaSpout.java:135)

If I register this class manually (doing kryo.register(java.nio.HeapByteBuffer.class) in Idea's debugger) the next error I receive is the following:  java.io.NotSerializableException: java.nio.HeapByteBuffer   in heron-api-0.14.6.jar!\com\esotericsoftware\kryo\Kryo.class

Should ByteBuffers be serialized before emission? I mean serialize() method in HeronPluggableSerializerDelegate

**Comment by billonahill** [comment]
I'm not sure about the answer to your question (others might know) but would you mind please posting this to the mailing list instead of filing a ticket for it? That's the best place to get help with questions.

**Comment by smirnp** [comment]
I have found the issue of the problem.   
Please check the contents of the org\apache\storm\spout\RawMultiScheme.class 
Storm's class is working, Heron one is not. So I have reimpelemented it in my topology. 
Please fix do not forget to fix it in future releases
Thanks!

**Comment by billonahill** [comment]
@smirnp I'm glad you rooted out the issue. Would you mind sharing your fix, ideally in the form of a patch?

**Comment by smirnp** [comment]
I should do a fork, patch it and make a pull request, right?

**Comment by billonahill** [comment]
Yes, make a fork, branch off the master, make the patch, push the branch, create a PR from that branch against origin master.

**Comment by hsun-cnnxty** [comment]
@smirnp I don't see the PR submitted. Can you share your fix?

-thanks
