### ISSUE TITLE
Make heron work with more recent bazel version

### ISSUE THREAD

**Issue by aahmed-se** [twitter/heron#1848]
using the latest version of bazel with brew it results in an error.

brew info bazel
bazel: stable 0.4.5 (bottled)

```bash
ERROR: /Users/a.ahmed/workspace/heron/tools/rules/pex_rules.bzl:236:24: Traceback (most recent call last):
	File "/Users/a.ahmed/workspace/heron/tools/rules/pex_rules.bzl", line 232
		rule(pex_binary_impl, executable = True, ..."), <2 more arguments>)})
	File "/Users/a.ahmed/workspace/heron/tools/rules/pex_rules.bzl", line 236, in rule
		attr.label(default = Label("//third_party/p..."), <2 more arguments>)
cfg parameter is mandatory when executable=True is provided. Please see https://www.bazel.build/versions/master/docs/skylark/rules.html#configurations for more details.
ERROR: /Users/a.ahmed/workspace/heron/tools/rules/pex_rules.bzl:248:24: Traceback (most recent call last):
	File "/Users/a.ahmed/workspace/heron/tools/rules/pex_rules.bzl", line 244
		rule(pex_test_impl, executable = True, at..."), <2 more arguments>)}, ...)
	File "/Users/a.ahmed/workspace/heron/tools/rules/pex_rules.bzl", line 248, in rule
		attr.label(default = Label("//third_party/p..."), <2 more arguments>)
cfg parameter is mandatory when executable=True is provided. Please see https://www.bazel.build/versions/master/docs/skylark/rules.html#configurations for more details.
ERROR: package contains errors: heron/proto.
ERROR: error loading package 'heron/proto': Extension file 'tools/rules/pex_rules.bzl' has errors.
INFO: Elapsed time: 0.457s
```

**Comment by aahmed-se** [comment]
closing as is duplicate of https://github.com/twitter/heron/issues/1769

**Comment by kramasamy** [comment]
@aahmed-se - there is a PR waiting to be merged actually. https://github.com/twitter/heron/pull/1776
