### ISSUE TITLE
Out of bounds exception when attempting to run a streamlet topology

### ISSUE THREAD

**Issue by lucperkins** [twitter/heron#2472]
I've been attempting to run this topology without any luck: https://gist.github.com/lucperkins/e7157cef307aaead239cf55f96ab68a2

This is the stack trace that I keep getting:

```log
[2017-10-20 15:02:11 -0700] [SEVERE] com.twitter.heron.instance.HeronInstance: Exception caught in thread: SlaveThread with id: 13 
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
    at java.util.ArrayList.rangeCheck(ArrayList.java:653)
    at java.util.ArrayList.get(ArrayList.java:429)
    at com.twitter.heron.common.basics.WakeableLooper.executeTasksOnWakeup(WakeableLooper.java:150)
    at com.twitter.heron.common.basics.WakeableLooper.runOnce(WakeableLooper.java:89)
    at com.twitter.heron.common.basics.WakeableLooper.loop(WakeableLooper.java:79)
    at com.twitter.heron.instance.Slave.run(Slave.java:180)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:748)
```

The `executeTasksOnWakeup` method appears to be the culprit and may not be thread safe:

```java
  private void executeTasksOnWakeup() {
    // Be careful here we could not use iterator, since it is possible that we may
    // add some items into this list during the iteration, which may cause
    // ConcurrentModificationException
    // We pre-get the size to avoid execute the tasks added during execution
    int s = tasksOnWakeup.size();
    for (int i = 0; i < s; i++) {
      tasksOnWakeup.get(i).run();
    }
  }
```

**Comment by srkukarni** [comment]
Am not able to reproduce this. Infact I'm getting a different error when I try running this.
java.lang.RuntimeException: java.io.NotSerializableException: com.twitter.heron.examples.streamlet.WireRequests$WireRequest

**Comment by maosongfu** [comment]
`executeTasksOnWakeup` is not thread-safe; we expect thread coordination from higher level externally

**Comment by srkukarni** [comment]
I believe this was due to a version mismatch between heron installed version and the topology.
