### ISSUE TITLE
Build Error on Mac OS Regarding PexPython and UI component

### ISSUE THREAD

**Issue by zuyu** [twitter/heron#808]
My Mac OS has `python 2.7.11`, and I encountered the following error from a fresh build:

```
$ bazel build --config=darwin heron/...

INFO: From PexPython heron/ui/src/python/heron-ui.pex:
Traceback (most recent call last):
  File "bazel-out/local_darwin-fastbuild/bin/3rdparty/pex/_pex", line 105, in <module>
    Main()
  File "bazel-out/local_darwin-fastbuild/bin/3rdparty/pex/_pex", line 84, in Main
    'Cannot exec() %r: file not found.' % main_filename
AssertionError: Cannot exec() '/private/var/tmp/_bazel_zzhang/3964dd02d192385870c24d7a89344f18/heron/bazel-out/local_darwin-fastbuild/bin/3rdparty/pex/_pex.runfiles/3rdparty/pex/_pex.py': file not found.
ERROR: /Users/zzhang/workspace/heron/heron/ui/src/python/BUILD:18:1: null failed: _pex failed: error executing command bazel-out/local_darwin-fastbuild/bin/3rdparty/pex/_pex --not-zip-safe --entry-point heron.ui.src.python.main bazel-out/local_darwin-fastbuild/bin/heron/ui/src/python/heron-ui.pex ... (remaining 1 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
```

**Comment by kramasamy** [comment]
Just wondering if you followed the instructions in the page 

http://twitter.github.io/heron/docs/developers/compiling/mac/

**Comment by zuyu** [comment]
@kramasamy Yes, I did, but got stuck in Step 8 due to the build error above.

**Comment by billonahill** [comment]
That's really strange. the _pex.py file can't another instance of find itself. Can you try changing Trace.shsout_log to return True and see what you get:
https://github.com/twitter/heron/blob/master/3rdparty/pex/pex/tracer.py#L64

You'll also want to pass `--verbose_failures` to `bazel build`.

**Comment by zuyu** [comment]
@billonahill Changing `Trace.should_log` does not print out any new error info, but enabling `--verbose_failures` does (see below).

```
INFO: From PexPython heron/ui/src/python/heron-ui.pex:
Traceback (most recent call last):
  File "bazel-out/local_darwin-fastbuild/bin/3rdparty/pex/_pex", line 105, in <module>
    Main()
  File "bazel-out/local_darwin-fastbuild/bin/3rdparty/pex/_pex", line 84, in Main
    'Cannot exec() %r: file not found.' % main_filename
AssertionError: Cannot exec() '/private/var/tmp/_bazel_zzhang/3964dd02d192385870c24d7a89344f18/heron/bazel-out/local_darwin-fastbuild/bin/3rdparty/pex/_pex.runfiles/3rdparty/pex/_pex.py': file not found.
ERROR: /Users/zzhang/workspace/heron/heron/ui/src/python/BUILD:18:1: null failed: _pex failed: error executing command
  (cd /private/var/tmp/_bazel_zzhang/3964dd02d192385870c24d7a89344f18/heron && \
  exec env - \
  bazel-out/local_darwin-fastbuild/bin/3rdparty/pex/_pex --not-zip-safe --entry-point heron.ui.src.python.main bazel-out/local_darwin-fastbuild/bin/heron/ui/src/python/heron-ui.pex bazel-out/local_darwin-fastbuild/bin/heron/ui/src/python/heron-ui.pex.manifest): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1: _pex failed: error executing command
  (cd /private/var/tmp/_bazel_zzhang/3964dd02d192385870c24d7a89344f18/heron && \
  exec env - \
  bazel-out/local_darwin-fastbuild/bin/3rdparty/pex/_pex --not-zip-safe --entry-point heron.ui.src.python.main bazel-out/local_darwin-fastbuild/bin/heron/ui/src/python/heron-ui.pex bazel-out/local_darwin-fastbuild/bin/heron/ui/src/python/heron-ui.pex.manifest): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
```

**Comment by billonahill** [comment]
@zuyu looks like `3rdparty/pex/_pex` failed to execute without much messaging as to why. Specfically this:

```
cd /private/var/tmp/_bazel_zzhang/3964dd02d192385870c24d7a89344f18/heron && \
  exec env - \
  bazel-out/local_darwin-fastbuild/bin/3rdparty/pex/_pex --not-zip-safe --entry-point \
  heron.ui.src.python.main bazel-out/local_darwin-fastbuild/bin/heron/ui/src/python/heron-ui.pex bazel-out/local_darwin-fastbuild/bin/heron/ui/src/python/heron-ui.pex.manifest
```

Best way to debug would be to add some print statements into `3rdparty/pex/_pex` to see identify it's failing and improve the messaging.

**Comment by zuyu** [comment]
I have no build errors in another Mac laptop, although the origin one still has the same build issue.
