### ISSUE TITLE
Getting Started - failed to get physical plan for topology ExclamationTopology

### ISSUE THREAD

**Issue by dsyu** [twitter/heron#822]
Following the Getting Started docs on linux mint 17.1:
- installed 0.14.0 tools and client install
- launched heron-tracker
- launched heron-ui
- submitted Exclamation Topology successfully

Trying to activate the Exclamation Topology and I'm getting this error:

> $ heron activate local ExclamationTopology
[2016-05-27 12:02:38 -0600] com.twitter.heron.common.basics.FileUtils SEVERE:  Failed to read from file.  
java.nio.file.NoSuchFileException: /home/<user>/.herondata/repository/state/local/pplans/ExclamationTopology
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.Files.readAllBytes(Files.java:3152)
	at com.twitter.heron.common.basics.FileUtils.readFromFile(FileUtils.java:90)
	at com.twitter.heron.statemgr.localfs.LocalFileSystemStateManager.getData(LocalFileSystemStateManager.java:106)
	at com.twitter.heron.statemgr.localfs.LocalFileSystemStateManager.getPhysicalPlan(LocalFileSystemStateManager.java:205)
	at com.twitter.heron.spi.statemgr.SchedulerStateManagerAdaptor.getPhysicalPlan(SchedulerStateManagerAdaptor.java:207)
	at com.twitter.heron.spi.utils.TMasterUtils.getRuntimeTopologyState(TMasterUtils.java:100)
	at com.twitter.heron.spi.utils.TMasterUtils.transitionTopologyState(TMasterUtils.java:115)
	at com.twitter.heron.scheduler.RuntimeManagerRunner.activateTopologyHandler(RuntimeManagerRunner.java:78)
	at com.twitter.heron.scheduler.RuntimeManagerRunner.call(RuntimeManagerRunner.java:56)
	at com.twitter.heron.scheduler.RuntimeManagerMain.callRuntimeManagerRunner(RuntimeManagerMain.java:369)
	at com.twitter.heron.scheduler.RuntimeManagerMain.manageTopology(RuntimeManagerMain.java:326)
	at com.twitter.heron.scheduler.RuntimeManagerMain.main(RuntimeManagerMain.java:251)
 
>[2016-05-27 12:02:38 -0600] com.twitter.heron.spi.utils.TMasterUtils SEVERE:  Failed to get physical plan for topology ExclamationTopology  
>[2016-05-27 12:02:38 -0600] com.twitter.heron.spi.utils.TMasterUtils SEVERE:  Topology still not initialized.  
>Exception in thread "main" java.lang.RuntimeException: Failed to ACTIVATE topology >ExclamationTopology
	at com.twitter.heron.scheduler.RuntimeManagerMain.main(RuntimeManagerMain.java:255)
Error: User main failed with status 1. Bailing out...
ERROR: Failed to activate topology 'ExclamationTopology'
INFO: Elapsed time: 0.412s.

There is in fact no file in the pplan directory.  

I also see errors in heron-tracker relating to the lack of zookeeper (I assume this is OK), and the following:
> 27 May 2016 12:08:54-INFO:tracker.py:108: Adding new topology: ExclamationTopology, state_manager: local
27 May 2016 12:08:54-INFO:main.py:74: ----------------------------------------------------------------------------------------------------
27 May 2016 12:08:54-INFO:topology.py:78: Registering a watch with uid: 9c01d0dd-0619-4347-be61-e627c29f13f9
27 May 2016 12:08:54-INFO:main.py:75: Tracker started
27 May 2016 12:08:54-INFO:tracker.py:395: No execution state found for: ExclamationTopology
27 May 2016 12:08:54-INFO:main.py:76: ----------------------------------------------------------------------------------------------------

in the tracker output.

**Comment by maosongfu** [comment]
It is possible a topology fails start normally, for instance, failing to start a component due to dependencies lacking, though it is submitted successfully.
Can you check the logs under: 
~/.herondata/topologies/{cluster}/{role}/{topologyName}/log-files/
and 
~/.herondata/topologies/{cluster}/{role}/{topologyName}/ heron-executor.stderr  && heron-executor.stdout
?

Can be a good idea to add this kind of debugging in doc.

**Comment by AMirFirouzi** [comment]
i have the same issue here, 

> com.twitter.heron.common.basics.FileUtils SEVERE:  Failed to read from file
> java.nio.file.NoSuchFileException: .../.herondata/repository/state/local/pplans/ExclamationTopology

it seems that no physical plan can be generated and then chain of errors appear because of that.

any ideas?

**Comment by maosongfu** [comment]
@AMirFirouzi 
It is possible a topology fails start normally, for instance, failing to start a component due to dependencies lacking, though it is submitted successfully.
Can you check the tmaster logs under:
~/.herondata/topologies/{cluster}/{role}/{topologyName}/log-files/
and
~/.herondata/topologies/{cluster}/{role}/{topologyName}/ heron-executor.stderr && heron-executor.stdout
?

**Comment by dsyu** [comment]
@maosongfu , neither of those files exist within my topologies log-files directory.

I do see this on container_1_word_2.log:

> [2016-05-31 07:40:36 -0600] com.twitter.heron.common.network.HeronClient SEVERE:  Failed to FinishConnect to endpoint: /127.0.0.1:57743 
java.net.ConnectException: Connection refused
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
        at com.twitter.heron.common.network.HeronClient.handleConnect(HeronClient.java:244)
        at com.twitter.heron.common.basics.NIOLooper.handleSelectedKeys(NIOLooper.java:115)
        at com.twitter.heron.common.basics.NIOLooper.access$000(NIOLooper.java:32)
        at com.twitter.heron.common.basics.NIOLooper$1.run(NIOLooper.java:45)
        at com.twitter.heron.common.basics.WakeableLooper.executeTasksOnWakeup(WakeableLooper.java:142)
        at com.twitter.heron.common.basics.WakeableLooper.runOnce(WakeableLooper.java:74)
        at com.twitter.heron.common.basics.WakeableLooper.loop(WakeableLooper.java:64)
        at com.twitter.heron.instance.Gateway.run(Gateway.java:155)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
 
>[2016-05-31 07:40:36 -0600] com.twitter.heron.network.StreamManagerClient INFO:  Stop writing due to not yet connected to Stream Manager.  
[2016-05-31 07:40:36 -0600] com.twitter.heron.network.StreamManagerClient INFO:  Stop reading due to not yet connected to Stream Manager.  
[2016-05-31 07:40:36 -0600] com.twitter.heron.network.StreamManagerClient WARNING:  Error connecting to Stream Manager with status: CONNECT_ERROR, Retrying...

**Comment by Udit93** [comment]
I am getting the same error on ubuntu 14.04. 

```
udit@udit:~$ heron activate local ExclamationTopology
[2016-05-31 23:16:20 +0530] com.twitter.heron.common.basics.FileUtils SEVERE:  Failed to read from file.  
java.nio.file.NoSuchFileException: /home/udit/.herondata/repository/state/local/pplans/ExclamationTopology
```

The pplans folder in above directory tree is empty.

Under the directory `~/.herondata/topologies/{cluster}/{role}/{topologyName}/log-files/` I notice the files 
> container_1_exclaim1_1.log.0
> container_1_word_2.log.0
giving same error as pointed out by dsyu.

```
[2016-05-31 14:52:14 +0530] com.twitter.heron.common.network.HeronClient SEVERE:  Failed to FinishConnect to endpoint: /127.0.0.1:50171 
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:740)
	at com.twitter.heron.common.network.HeronClient.handleConnect(HeronClient.java:244)
	at com.twitter.heron.common.basics.NIOLooper.handleSelectedKeys(NIOLooper.java:115)
	at com.twitter.heron.common.basics.NIOLooper.access$000(NIOLooper.java:32)
	at com.twitter.heron.common.basics.NIOLooper$1.run(NIOLooper.java:45)
	at com.twitter.heron.common.basics.WakeableLooper.executeTasksOnWakeup(WakeableLooper.java:142)
	at com.twitter.heron.common.basics.WakeableLooper.runOnce(WakeableLooper.java:74)
	at com.twitter.heron.common.basics.WakeableLooper.loop(WakeableLooper.java:64)
	at com.twitter.heron.instance.Gateway.run(Gateway.java:155)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```
 
```
File "heron-executor.stdout" reports the following error - 
2016-05-31 17:36:57: Running container_1_word_2 process as /usr/lib/jvm/default-java/bin/java -Xmx320M -Xms320M -Xmn160M -XX:MaxPermSize=128M -XX:PermSize=128M -XX:ReservedCodeCacheSize=64M -XX:+CMSScavengeBeforeRemark -XX:TargetSurvivorRatio=90 -XX:+PrintCommandLineFlags -verbosegc -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintGCDateStamps -XX:+PrintGCCause -XX:+PrintPromotionFailure -XX:+PrintTenuringDistribution -XX:+PrintHeapAtGC -XX:+HeapDumpOnOutOfMemoryError -XX:+UseConcMarkSweepGC -XX:ParallelGCThreads=4 -Xloggc:log-files/gc.container_1_word_2.log -XX:+HeapDumpOnOutOfMemoryError -Djava.net.preferIPv4Stack=true -cp ./heron-core/lib/instance/*:heron-examples.jar com.twitter.heron.instance.HeronInstance ExclamationTopology ExclamationTopology4dd1e087-a0cf-4ea5-9e87-4217c412c646 container_1_word_2 word 2 0 stmgr-1 58491 50621 ./heron-conf/heron_internals.yaml
```
and 

`2016-05-31 17:36:57: Running container_1_exclaim1_1 process as /usr/lib/jvm/default-java/bin/java -Xmx320M -Xms320M -Xmn160M -XX:MaxPermSize=128M -XX:PermSize=128M -XX:ReservedCodeCacheSize=64M -XX:+CMSScavengeBeforeRemark -XX:TargetSurvivorRatio=90 -XX:+PrintCommandLineFlags -verbosegc -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintGCDateStamps -XX:+PrintGCCause -XX:+PrintPromotionFailure -XX:+PrintTenuringDistribution -XX:+PrintHeapAtGC -XX:+HeapDumpOnOutOfMemoryError -XX:+UseConcMarkSweepGC -XX:ParallelGCThreads=4 -Xloggc:log-files/gc.container_1_exclaim1_1.log -XX:+HeapDumpOnOutOfMemoryError -Djava.net.preferIPv4Stack=true -cp ./heron-core/lib/instance/*:heron-examples.jar com.twitter.heron.instance.HeronInstance ExclamationTopology ExclamationTopology4dd1e087-a0cf-4ea5-9e87-4217c412c646 container_1_exclaim1_1 exclaim1 1 0 stmgr-1 58491 50621 ./heron-conf/heron_internals.yaml
`

The error being **HeapDumpOnOutOfMemoryError**. Is it possible that this error is caused because zookeeper was not setup for State Manager

**Comment by aaronshan** [comment]
I also get this error in centos7 and I resolved it by installing libunwind. I think this problem should due to lacking native c++ dependency. @dsyu @AMirFirouzi @Udit93

**Comment by kramasamy** [comment]
the c++ binaries need to be statically linked - we do mostly static option and because of this standard libraries and libunwind are not statically linked.

**Comment by aaronshan** [comment]
@kramasamy @maosongfu , I also get this error in centos6, when I try use my aforementioned method to resolve it, but I failed. If I want use heron in centos6, should I do?

**Comment by jipinxieshen** [comment]
I also get this error in centos7! Hope can be solved

**Comment by maosongfu** [comment]
@jipinxieshen 
Checked the heron-executor.stdout provided by @aaronshan , and found:

heron-tmaster exited with status 256
stmgr-1 exited with status 256

So pretty sure the issue is caused by lacking dependencies to start C++ program; but it is wired that log-info is missing in heron-executor.stderr, so currently no way to know what those dependencies are.

You can diagnose by run the stream mgr's cmd directly in terminal, check the output and figure out the lacking dependencies.

We are working in progress to relief your issues too:
1. #505 
2. #853

**Comment by XciD** [comment]
I've got this error by running the stmgr-1 directly : 

```
./heron-core/bin/heron-stmgr: error while loading shared libraries: libunwind.so.8: cannot open shared object file: No such file or directory
```

Resolved by installing libunwind

**Comment by aaronshan** [comment]
@jipinxieshen If you use centos7, you nedd install libunwind, If you use centos6, you need upgrade your gcc and glibc version.

**Comment by maosongfu** [comment]
#853 is fixed. Now people can figure out reasons failed to start process from:
~/.herondata/topologies/{cluster}/{role}/{topologyName}/ heron-executor.stdout

**Comment by deveshagrawal** [comment]
Faced exact same error while using ubuntu 16 while following the getting started guide.

There are some dependencies on linux:

Following library files fixed it for me:
`sudo apt-get install git build-essential automake cmake libtool zip libunwind-setjmp0-dev zlib1g-dev unzip pkg-config -y`

**Comment by lilalinda** [comment]
With Ubuntu 14.04.4 server, I faced the same issue of the missing file 
`/home/USER/.herondata/repository/state/local/pplans/ExclamationTopology`
and this also resulted in an empty diagram or image for Logical Topology in the heron-ui web view as well as empty metrics and containers and such.

These minimal dependencies solved it for me:
`$ sudo apt-get install unzip libunwind-setjmp0`
and the heron-ui topology view now contains these diagrams (circled):
![heron-fixed](https://cloud.githubusercontent.com/assets/1231235/16008740/a37e643c-3179-11e6-8398-b4e2d81bf2cd.png)

But still no log files
`heron-executor.stderr` or `heron-executor.stdout`
in
`.herondata/topologies/local/USER/ExclamationTopology/log-files/`

**Comment by Udit93** [comment]
I installed the missing dependencies on my ubuntu 14.04
However when I run command _heron kill --verbose local ExclamationTopology_ , I fails giving error:

[2016-06-13 22:19:46 +0530] sun.net.www.protocol.http.HttpURLConnection FINEST:  ProxySelector Request for http://udit:48269/kill  
[2016-06-13 22:19:46 +0530] com.twitter.heron.spi.common.NetworkUtils SEVERE:  Failed to close OutputStream:  
java.net.ConnectException: Connection refused 

Someone please help.

**Comment by maosongfu** [comment]
@lilalinda 
`heron-executor.stderr` or `heron-executor.stdout` is in
`.herondata/topologies/local/USER/ExclamationTopology/`
, rather than in 
`.herondata/topologies/local/USER/ExclamationTopology/log-files/`

**Comment by maosongfu** [comment]
@Udit93 
https://github.com/twitter/heron/pull/902/files
```
It is also possible that the host has an issue with resolving localhost. To check, run the following command in a shell.

$ python -c "import socket; print socket.gethostbyname(socket.gethostname())"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
If the output looks like a normal IP address, such as 127.0.0.1, you don't have this issue. If the output is similar to the above, you need to modify the /etc/hosts file to correctly resolve localhost, as shown below.

Run the following command, whose output is your computer's hostname.

$ python -c "import socket; print socket.gethostname()"
Open the /etc/hosts file as superuser and find a line containing

127.0.0.1   localhost
Append your hostname after the word "localhost" on the line. For example, if your hostname was tw-heron, then the line should look like the following:

127.0.0.1   localhost   tw-heron
Save the file. The change should usually be reflected immediately, although rebooting might be necessary depending on your platform.
```

**Comment by lilalinda** [comment]
@maosongfu Yes, you are right that the log files are indeed a level higher than expected.  Now I declare success with the local getting-started example. Thanks!

**Comment by Udit93** [comment]
@maosongfu The output I receive is 127.0.0.1

**Comment by ababushkin** [comment]
Anyone have a solution for this issue on Mac OS?
