### ISSUE TITLE
Running example ExclamationTopology gives java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by bretlowery** [twitter/heron#830]
After installing pre-compiled binary for Mac OSX standalone:

heron submit local   ~/.heron/examples/heron-examples.jar \ 
  com.twitter.heron.examples.ExclamationTopology 

returns:

Exception in thread "main" java.lang.NoClassDefFoundError:  #
Caused by: java.lang.ClassNotFoundException:  #
	at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
ERROR: Unable to execute topology main class

**Comment by bretlowery** [comment]
Checking my path, install locations, etc.

**Comment by kramasamy** [comment]
@bretlowery - Wondering during the installation whether you used the --user option?  If that is the case it installs heron under ~/.heron.  Let us know.

**Comment by bretlowery** [comment]
I uninstalled and reinstalled and it worked. I think I missed a PATH export the first time around.
