### ISSUE TITLE
[Local Sheduler] "Failed to start Stream manager"

### ISSUE THREAD

**Issue by longdafeng** [twitter/heron#834]
Thanks in advance.

Environment:
OS :  Redhat ehel 7.2   
jdk:  1.8

I have compiled heron source code, install heron with the compiled package

```
#cd bazel-bin/scripts/packages/
#./heron-api-install.sh --user
#./heron-client-install.sh --user
#./heron-tools-install.sh --user
#mv heron-core.tar.gz ~/.heron/
#cd ~/.heron
#tar -xzf heron-core.tar.gz
```   

run the example:
```
heron submit local ~/.heron/examples/heron-examples.jar  com.twitter.heron.examples.ExclamationTopology ExclamationTopology
```

logs
[log-files.ZIP](http://42.121.19.155/log-files.ZIP)

```
[2016-05-30 12:38:25 +0800] com.twitter.heron.common.network.HeronClient SEVERE:  Failed to FinishConnect to endpoint: /127.0.0.1:53098
java.net.ConnectException: Connection refused
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
        at com.twitter.heron.common.network.HeronClient.handleConnect(HeronClient.java:244)
        at com.twitter.heron.common.basics.NIOLooper.handleSelectedKeys(NIOLooper.java:115)
        at com.twitter.heron.common.basics.NIOLooper.access$000(NIOLooper.java:32)
        at com.twitter.heron.common.basics.NIOLooper$1.run(NIOLooper.java:45)
        at com.twitter.heron.common.basics.WakeableLooper.executeTasksOnWakeup(WakeableLooper.java:142)
        at com.twitter.heron.common.basics.WakeableLooper.runOnce(WakeableLooper.java:74)
        at com.twitter.heron.common.basics.WakeableLooper.loop(WakeableLooper.java:64)
        at com.twitter.heron.instance.Gateway.run(Gateway.java:155)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:756)

[2016-05-30 12:38:25 +0800] com.twitter.heron.common.network.HeronClient SEVERE:  Failed to FinishConnect to endpoint: /127.0.0.1:39894
java.net.ConnectException: Connection refused
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
        at com.twitter.heron.common.network.HeronClient.handleConnect(HeronClient.java:244)
        at com.twitter.heron.common.basics.NIOLooper.handleSelectedKeys(NIOLooper.java:115)
        at com.twitter.heron.common.basics.NIOLooper.access$000(NIOLooper.java:32)
        at com.twitter.heron.common.basics.NIOLooper$1.run(NIOLooper.java:45)
        at com.twitter.heron.common.basics.WakeableLooper.executeTasksOnWakeup(WakeableLooper.java:142)
        at com.twitter.heron.common.basics.WakeableLooper.runOnce(WakeableLooper.java:74)
        at com.twitter.heron.common.basics.WakeableLooper.loop(WakeableLooper.java:64)
        at com.twitter.heron.instance.Gateway.run(Gateway.java:155)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:756)

[2016-05-30 12:38:25 +0800] com.twitter.heron.network.StreamManagerClient INFO:  Stop writing due to not yet connected to Stream Manager.
[2016-05-30 12:38:25 +0800] com.twitter.heron.network.StreamManagerClient INFO:  Stop reading due to not yet connected to Stream Manager.
```

ps -ef|grep heron
```
admin    181603      1  0 12:38 pts/0    00:00:01 /opt/taobao/java/bin/java -cp ./heron-core/lib/scheduler/*:./heron-core/lib/packing/*:./heron-core/lib/statemgr/* com.twitter.heron.scheduler.SchedulerMain --cluster local --role admin --environment default --topology_name ExclamationTopology --topology_jar /home/admin/.heron/examples/heron-examples.jar --http_port 45534
admin    181652 181603  0 12:38 pts/0    00:00:00 python2.7 ./heron-core/bin/heron-executor 0 ExclamationTopology ExclamationTopology5661f7ee-3270-47eb-9372-4007c65a1712 ExclamationTopology.defn 1:word:2:0:exclaim1:1:0 LOCALMODE /home/admin/.herondata/repository/state/local ./heron-core/bin/heron-tmaster ./heron-core/bin/heron-stmgr ./heron-core/lib/metricsmgr/* "LVhYOitIZWFwRHVtcE9uT3V0T2ZNZW1vcnlFcnJvcg&equals;&equals;" heron-examples.jar 59215 45101 53051 ./heron-conf/heron_internals.yaml exclaim1:536870912,word:536870912 "" jar /home/admin/.heron/examples/heron-examples.jar /opt/taobao/java 37275 ./heron-core/bin/heron-shell 34822 local admin default ./heron-core/lib/instance/* ./heron-conf/metrics_sinks.yaml ./heron-core/lib/scheduler/*:./heron-core/lib/packing/*:./heron-core/lib/statemgr/* 36020
admin    181655 181603  0 12:38 pts/0    00:00:00 python2.7 ./heron-core/bin/heron-executor 1 ExclamationTopology ExclamationTopology5661f7ee-3270-47eb-9372-4007c65a1712 ExclamationTopology.defn 1:word:2:0:exclaim1:1:0 LOCALMODE /home/admin/.herondata/repository/state/local ./heron-core/bin/heron-tmaster ./heron-core/bin/heron-stmgr ./heron-core/lib/metricsmgr/* "LVhYOitIZWFwRHVtcE9uT3V0T2ZNZW1vcnlFcnJvcg&equals;&equals;" heron-examples.jar 53098 60037 35245 ./heron-conf/heron_internals.yaml exclaim1:536870912,word:536870912 "" jar /home/admin/.heron/examples/heron-examples.jar /opt/taobao/java 51229 ./heron-core/bin/heron-shell 39894 local admin default ./heron-core/lib/instance/* ./heron-conf/metrics_sinks.yaml ./heron-core/lib/scheduler/*:./heron-core/lib/packing/*:./heron-core/lib/statemgr/* 42429
admin    181675 181652  0 12:38 pts/0    00:00:00 python2.7 ./heron-core/bin/heron-shell --port=37275 --log_file_prefix=log-files/heron-shell.log
admin    181683 181655  0 12:38 pts/0    00:00:00 python2.7 ./heron-core/bin/heron-shell --port=51229 --log_file_prefix=log-files/heron-shell.log
admin    181684 181652  1 12:38 pts/0    00:00:01 /opt/taobao/java/bin/java -Xmx1024M -XX:+PrintCommandLineFlags -verbosegc -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintGCDateStamps -XX:+PrintGCCause -XX:+PrintPromotionFailure -XX:+PrintTenuringDistribution -XX:+PrintHeapAtGC -XX:+HeapDumpOnOutOfMemoryError -XX:+UseConcMarkSweepGC -XX:+PrintCommandLineFlags -Xloggc:log-files/gc.metricsmgr.log -Djava.net.preferIPv4Stack=true -cp ./heron-core/lib/metricsmgr/* com.twitter.heron.metricsmgr.MetricsManager metricsmgr-0 34822 ExclamationTopology ExclamationTopology5661f7ee-3270-47eb-9372-4007c65a1712 ./heron-conf/heron_internals.yaml ./heron-conf/metrics_sinks.yaml
admin    181704 181655  2 12:38 pts/0    00:00:03 /opt/taobao/java/bin/java -Xmx320M -Xms320M -Xmn160M -XX:MaxPermSize=128M -XX:PermSize=128M -XX:ReservedCodeCacheSize=64M -XX:+CMSScavengeBeforeRemark -XX:TargetSurvivorRatio=90 -XX:+PrintCommandLineFlags -verbosegc -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintGCDateStamps -XX:+PrintGCCause -XX:+PrintPromotionFailure -XX:+PrintTenuringDistribution -XX:+PrintHeapAtGC -XX:+HeapDumpOnOutOfMemoryError -XX:+UseConcMarkSweepGC -XX:ParallelGCThreads=4 -Xloggc:log-files/gc.container_1_word_2.log -XX:+HeapDumpOnOutOfMemoryError -Djava.net.preferIPv4Stack=true -cp ./heron-core/lib/instance/*:heron-examples.jar com.twitter.heron.instance.HeronInstance ExclamationTopology ExclamationTopology5661f7ee-3270-47eb-9372-4007c65a1712 container_1_word_2 word 2 0 stmgr-1 53098 39894 ./heron-conf/heron_internals.yaml
admin    181732 181655  2 12:38 pts/0    00:00:03 /opt/taobao/java/bin/java -Xmx320M -Xms320M -Xmn160M -XX:MaxPermSize=128M -XX:PermSize=128M -XX:ReservedCodeCacheSize=64M -XX:+CMSScavengeBeforeRemark -XX:TargetSurvivorRatio=90 -XX:+PrintCommandLineFlags -verbosegc -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintGCDateStamps -XX:+PrintGCCause -XX:+PrintPromotionFailure -XX:+PrintTenuringDistribution -XX:+PrintHeapAtGC -XX:+HeapDumpOnOutOfMemoryError -XX:+UseConcMarkSweepGC -XX:ParallelGCThreads=4 -Xloggc:log-files/gc.container_1_exclaim1_1.log -XX:+HeapDumpOnOutOfMemoryError -Djava.net.preferIPv4Stack=true -cp ./heron-core/lib/instance/*:heron-examples.jar com.twitter.heron.instance.HeronInstance ExclamationTopology ExclamationTopology5661f7ee-3270-47eb-9372-4007c65a1712 container_1_exclaim1_1 exclaim1 1 0 stmgr-1 53098 39894 ./heron-conf/heron_internals.yaml
admin    181791 181655  1 12:38 pts/0    00:00:01 /opt/taobao/java/bin/java -Xmx1024M -XX:+PrintCommandLineFlags -verbosegc -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintGCDateStamps -XX:+PrintGCCause -XX:+PrintPromotionFailure -XX:+PrintTenuringDistribution -XX:+PrintHeapAtGC -XX:+HeapDumpOnOutOfMemoryError -XX:+UseConcMarkSweepGC -XX:+PrintCommandLineFlags -Xloggc:log-files/gc.metricsmgr.log -Djava.net.preferIPv4Stack=true -cp ./heron-core/lib/metricsmgr/* com.twitter.heron.metricsmgr.MetricsManager metricsmgr-1 39894 ExclamationTopology ExclamationTopology5661f7ee-3270-47eb-9372-4007c65a1712 ./heron-conf/heron_internals.yaml ./heron-conf/metrics_sinks.yaml
admin    181931  28300  1 12:38 pts/0    00:00:01 python2.7 ./heron-tracker
admin    181975  28300  1 12:39 pts/0    00:00:01 python2.7 ./heron-ui
admin    182288  35370  0 12:40 pts/1    00:00:00 grep --color=auto heron
```

**Comment by longdafeng** [comment]
From the scheduler log, it didn't started Stream manager

```
[2016-05-30 12:38:24 +0800] com.twitter.heron.scheduler.local.LocalScheduler INFO:  Executor command line: [./heron-core/bin/heron-executor, 0, ExclamationTopology, ExclamationTopology5661f7ee-3270-47eb-9372-4007c65a1712, ExclamationTopology.defn, 1:word:2:0:exclaim1:1:0, LOCALMODE, /home/admin/.herondata/repository/state/local, ./heron-core/bin/heron-tmaster, ./heron-core/bin/heron-stmgr, ./heron-core/lib/metricsmgr/*, "LVhYOitIZWFwRHVtcE9uT3V0T2ZNZW1vcnlFcnJvcg&equals;&equals;", heron-examples.jar, 59215, 45101, 53051, ./heron-conf/heron_internals.yaml, exclaim1:536870912,word:536870912, "", jar, /home/admin/.heron/examples/heron-examples.jar, /opt/taobao/java, 37275, ./heron-core/bin/heron-shell, 34822, local, admin, default, ./heron-core/lib/instance/*, ./heron-conf/metrics_sinks.yaml, ./heron-core/lib/scheduler/*:./heron-core/lib/packing/*:./heron-core/lib/statemgr/*, 36020]
[2016-05-30 12:38:24 +0800] com.twitter.heron.spi.common.ShellUtils INFO:  $> [./heron-core/bin/heron-executor, 0, ExclamationTopology, ExclamationTopology5661f7ee-3270-47eb-9372-4007c65a1712, ExclamationTopology.defn, 1:word:2:0:exclaim1:1:0, LOCALMODE, /home/admin/.herondata/repository/state/local, ./heron-core/bin/heron-tmaster, ./heron-core/bin/heron-stmgr, ./heron-core/lib/metricsmgr/*, "LVhYOitIZWFwRHVtcE9uT3V0T2ZNZW1vcnlFcnJvcg&equals;&equals;", heron-examples.jar, 59215, 45101, 53051, ./heron-conf/heron_internals.yaml, exclaim1:536870912,word:536870912, "", jar, /home/admin/.heron/examples/heron-examples.jar, /opt/taobao/java, 37275, ./heron-core/bin/heron-shell, 34822, local, admin, default, ./heron-core/lib/instance/*, ./heron-conf/metrics_sinks.yaml, ./heron-core/lib/scheduler/*:./heron-core/lib/packing/*:./heron-core/lib/statemgr/*, 36020]
[2016-05-30 12:38:24 +0800] com.twitter.heron.scheduler.local.LocalScheduler INFO:  Started the executor for container: 0
[2016-05-30 12:38:24 +0800] com.twitter.heron.scheduler.local.LocalScheduler INFO:  Starting a new executor for container: 1
[2016-05-30 12:38:24 +0800] com.twitter.heron.scheduler.local.LocalScheduler INFO:  Executor command line: [./heron-core/bin/heron-executor, 1, ExclamationTopology, ExclamationTopology5661f7ee-3270-47eb-9372-4007c65a1712, ExclamationTopology.defn, 1:word:2:0:exclaim1:1:0, LOCALMODE, /home/admin/.herondata/repository/state/local, ./heron-core/bin/heron-tmaster, ./heron-core/bin/heron-stmgr, ./heron-core/lib/metricsmgr/*, "LVhYOitIZWFwRHVtcE9uT3V0T2ZNZW1vcnlFcnJvcg&equals;&equals;", heron-examples.jar, 53098, 60037, 35245, ./heron-conf/heron_internals.yaml, exclaim1:536870912,word:536870912, "", jar, /home/admin/.heron/examples/heron-examples.jar, /opt/taobao/java, 51229, ./heron-core/bin/heron-shell, 39894, local, admin, default, ./heron-core/lib/instance/*, ./heron-conf/metrics_sinks.yaml, ./heron-core/lib/scheduler/*:./heron-core/lib/packing/*:./heron-core/lib/statemgr/*, 42429]
[2016-05-30 12:38:24 +0800] com.twitter.heron.scheduler.local.LocalScheduler INFO:  Waiting for container 0 to finish.
[2016-05-30 12:38:24 +0800] com.twitter.heron.spi.common.ShellUtils INFO:  $> [./heron-core/bin/heron-executor, 1, ExclamationTopology, ExclamationTopology5661f7ee-3270-47eb-9372-4007c65a1712, ExclamationTopology.defn, 1:word:2:0:exclaim1:1:0, LOCALMODE, /home/admin/.herondata/repository/state/local, ./heron-core/bin/heron-tmaster, ./heron-core/bin/heron-stmgr, ./heron-core/lib/metricsmgr/*, "LVhYOitIZWFwRHVtcE9uT3V0T2ZNZW1vcnlFcnJvcg&equals;&equals;", heron-examples.jar, 53098, 60037, 35245, ./heron-conf/heron_internals.yaml, exclaim1:536870912,word:536870912, "", jar, /home/admin/.heron/examples/heron-examples.jar, /opt/taobao/java, 51229, ./heron-core/bin/heron-shell, 39894, local, admin, default, ./heron-core/lib/instance/*, ./heron-conf/metrics_sinks.yaml, ./heron-core/lib/scheduler/*:./heron-core/lib/packing/*:./heron-core/lib/statemgr/*, 42429]
```

then how to start stream manager

**Comment by kramasamy** [comment]
@longdafeng - there is no need to mv heron-core.tar.gz to ~/.heron - heron-client-install.sh --user will automatically install heron-core.tar.gz. stream manager is started automatically when you launch the topology.

@maosongfu - can you please take a look at this?

**Comment by maosongfu** [comment]
Stream mgr is started by heron-executor, rather than by scheduler directly.

It is possible a topology fails start normally, for instance, failing to start a component due to dependencies lacking, though it is submitted successfully.
Can you check the logs under: 
~/.herondata/topologies/{cluster}/{role}/{topologyName}/log-files/
and 
~/.herondata/topologies/{cluster}/{role}/{topologyName}/ heron-executor.stderr && heron-executor.stdout
?

Can be a good idea to add this kind of debugging in doc.

**Comment by longdafeng** [comment]
Thanks @kramasamy  @maosongfu 

I have uploaded the log  in the first issue

I found some log in ~/.herondata/topologies/{cluster}/{role}/{topologyName}/ heron-executor.stdout

```
2016-05-30 12:56:38: Running stmgr-1 process as ./heron-core/bin/heron-stmgr ExclamationTopology ExclamationTopology5661f7ee-3270-47eb-9372-4007c65a1712 ExclamationTopology.defn LOCALMODE /home/admin/.herondata/repository/state/local stmgr-1 container_1_word_2,container_1_exclaim1_1 38133 33156 46759 ./heron-conf/heron_internals.yaml
2016-05-30 12:56:38: Logging pid 184367 to file stmgr-1.pid
2016-05-30 12:56:38: stmgr-1 exited with status 32512
```

[heron-executor.stdout.zip](https://github.com/twitter/heron/files/290205/heron-executor.stdout.zip)
[log-files.zip](https://github.com/twitter/heron/files/290207/log-files.zip)

**Comment by longdafeng** [comment]
heron-executor.stderr file is empty

**Comment by longdafeng** [comment]
fix the problem

libunwind install directory should be set in the shared library path

**Comment by maosongfu** [comment]
Yes, we noticed this earlier: #505 
It is nice to add:
1. How to investigate normal failures with logs,
2. Document clearly the dependencies (native system libraries) c++ executable relies on

into the getting-started guide. @kramasamy

**Comment by kramasamy** [comment]
#505 is prioritized for next release.

**Comment by maosongfu** [comment]
#853 is also working in progress.

**Comment by maosongfu** [comment]
#853 is fixed. Now people can figure out reasons failed to start process from:
~/.herondata/topologies/{cluster}/{role}/{topologyName}/ heron-executor.stdout

**Comment by jieliu3** [comment]
@longdafeng i put libunwind into LD_LIBRARY_PATH ,then resubmit ，problem also is flying ..
@maosongfu  "2. Document clearly the dependencies (native system libraries) c++ executable relies on into the getting-started guide"  ，i can't find this update in http://twitter.github.io/heron/docs/getting-started/

**Comment by maosongfu** [comment]
@jieliu3 
1. Now you can check "~/.herondata/topologies/{cluster}/{role}/{topologyName}/ heron-executor.stdout" to figure out the reason failing to start a component.

"2. Document clearly the dependencies (native system libraries) c++ executable relies on into the getting-started guide"
This is working in progress. Pull request is here: #877

**Comment by jieliu3** [comment]
@maosongfu

**Comment by jieliu3** [comment]
@maosongfu  In “~/.herondata/topologies/{cluster}/{role}/{topologyName}/ heron-executor.stdout" ,error tips :

**Comment by jieliu3** [comment]
@maosongfu  In heron-executor.stdout log file，there is stmgr existed info ：“stmgr-1 exited with status 32512”，“heron-tmaster exited with status 32512”，while in log-files/container_1_exclaim1_1.log.0 ,there is error info：“com.twitter.heron.common.network.HeronClient SEVERE:  Failed to FinishConnect to endpoint: /127.0.0.1:48462  java.net.ConnectException: Connection refused“。i  execute heron-stmgr single,there is error info :./heron-stmgr: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by ./heron-stmgr)
./heron-stmgr: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.19' not found (required by ./heron-stmgr)
./heron-stmgr: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.16' not found (required by ./heron-stmgr)

**Comment by jieliu3** [comment]
it'ok when switch to centos 7 (glibc 2.17) @maosongfu

**Comment by maosongfu** [comment]
Resolved.
