### ISSUE TITLE
Topology submit errors in logs

### ISSUE THREAD

**Issue by lohithsamaga** [twitter/heron#858]
Hi,
I am running heron on Ubuntu 14.04 with oracle jdk 1.8.0_u91.

When I submit the ExclamationTopology, it looks OK. However, in heron-executor.stdout, I see the following lines:
`2016-06-03 14:55:31: Running heron-tmaster process as ./heron-core/bin/heron-tmaster 34554 37834 41519 ETopo03 ETopo031ec80dd9-fae2-43a4-9065-741780825723 LOCALMODE /home/ubu002/.herondata/repository/state/local stmgr-1 ./heron-conf/heron_internals.yaml ./heron-conf/metrics_sinks.yaml 39885
2016-06-03 14:55:31: Running stmgr-1 process as ./heron-core/bin/heron-stmgr ETopo03 ETopo031ec80dd9-fae2-43a4-9065-741780825723 ETopo03.defn LOCALMODE /home/ubu002/.herondata/repository/state/local stmgr-1 container_1_word_2,container_1_exclaim1_1 35484 39327 37004 ./heron-conf/heron_internals.yaml
2016-06-03 14:55:31: Logging pid 1834 to file heron-tmaster.pid
2016-06-03 14:55:31: Logging pid 1835 to file stmgr-1.pid
2016-06-03 14:55:31: heron-tmaster exited with status 32512
2016-06-03 14:55:31: stmgr-1 exited with status 32512
`

This set of messages repeats every few seconds.
When I try to activate the topology using `heron activate local ETopo03`, I get the following error:

`java.nio.file.NoSuchFileException: /home/ubu002/.herondata/repository/state/local/pplans/ETopo03
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
        at java.nio.file.Files.newByteChannel(Files.java:361)
        at java.nio.file.Files.newByteChannel(Files.java:407)
        at java.nio.file.Files.readAllBytes(Files.java:3152)
...`
Indeed, the directory `~/.herondata/repository/state/local/pplans` is empty.

What did I do wrong?

**Comment by aaronshan** [comment]
you can run this code, paste your output
```
cd /home/ubu002/.herondata/topologies/local/ubu002/ETopo03
./heron-core/bin/heron-stmgr ETopo03 ETopo031ec80dd9-fae2-43a4-9065-741780825723 ETopo03.defn LOCALMODE /home/ubu002/.herondata/repository/state/local stmgr-1 container_1_word_2,container_1_exclaim1_1 35484 39327 37004 ./heron-conf/heron_internals.yaml
```

**Comment by nlu90** [comment]
@lohithsamaga If you keep seeing following messages:
```shell
2016-06-03 14:55:31: heron-tmaster exited with status 32512 
2016-06-03 14:55:31: stmgr-1 exited with status 32512
```
It means your topology is not started successfully. And based on the status code, 32512 implies that certain c++ lib is missing.

Can you check the log files of tamster and stmgr in `~/.herondata/topologies/{cluster}/{user}/{topology}` to find out the actual problem?

**Comment by maosongfu** [comment]
#853 is fixed. Now people can figure out reasons failed to start process from:
~/.herondata/topologies/{cluster}/{role}/{topologyName}/ heron-executor.stdout
