### ISSUE TITLE
Error in ubuntu build

### ISSUE THREAD

**Issue by supunkamburugamuve** [twitter/heron#876]
Getting the following error while building the master in Ubuntu 14.04

pex requirements: ['requests==2.3.0', 'tornado==4.0.2']
**** Failed to install certifi-2016.2.28. stdout:

**** Failed to install certifi-2016.2.28. stderr:
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/local/lib/python2.7/dist-packages/setuptools/__init__.py", line 11, in <module>
    from setuptools.extension import Extension
  File "/usr/local/lib/python2.7/dist-packages/setuptools/extension.py", line 8, in <module>
    from .dist import _get_unpatched
  File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 21, in <module>
    packaging = pkg_resources.packaging
AttributeError: 'module' object has no attribute 'packaging'

**Comment by billonahill** [comment]
Have you searched for the problem? Looks like this might be related:
http://stackoverflow.com/questions/28967785/attribute-error-installing-with-pip/30310206#30310206

**Comment by supunkamburugamuve** [comment]
Thanks @billonahill, the answer here worked.
