### ISSUE TITLE
Error messages in classloader are not descriptive

### ISSUE THREAD

**Issue by ajorgensen** [twitter/heron#882]
```
Exception in thread "main" java.lang.NullPointerException
       at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:307)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
       at com.twitter.heron.spi.utils.ReflectionUtils.newInstance(ReflectionUtils.java:31)
       at com.twitter.heron.spi.utils.ReflectionUtils.newInstance(ReflectionUtils.java:25)
       at com.twitter.heron.scheduler.SubmitterMain.submitTopology(SubmitterMain.java:376)
       at com.twitter.heron.scheduler.SubmitterMain.main(SubmitterMain.java:315)
```

Heron is using reflection here to try and load classes based on config files. In this case it was trying to load the uploader class when a uploader.yaml file was not provided. I think we could both make these error messages more descriptive or fail fast in the event of a missing yaml file with no default values.

**Comment by billonahill** [comment]
+1 the above exception should never happen.

@ajorgensen can you describe a simple way to reproduce? Does this happen when a given implementation class is not specified or not found in the yaml?

**Comment by maosongfu** [comment]
@billonahill This can happen when the classname to create is empty. @ajorgensen Triggered this exception by not passing a value for the required config.

**Comment by ajorgensen** [comment]
Correct I was missing a required config file specifically `uploader.yaml`. I'm not sure if theres a list of the minimum config thats needed to actually run the heron cli. If you turn on the debug logging when running a cli command you can see it checking to see if theres a list of config files and if they are not there it just continues. For example:

```
[2016-06-09 18:58:35 +0000] com.twitter.heron.common.config.ConfigReader FINE:  Reading config stream
[2016-06-09 18:58:36 +0000] com.twitter.heron.common.config.ConfigReader FINE:  Successfully read config
[2016-06-09 18:58:36 +0000] com.twitter.heron.common.config.ConfigReader FINE:  Reading config stream
[2016-06-09 18:58:36 +0000] com.twitter.heron.common.config.ConfigReader FINE:  Successfully read config
[2016-06-09 18:58:36 +0000] com.twitter.heron.common.config.ConfigReader FINE:  Config file /home/ajorgensen/heron-client/conf/production/cluster.yaml does not exist
[2016-06-09 18:58:36 +0000] com.twitter.heron.common.config.ConfigReader FINE:  Config file /home/ajorgensen/heron-client/conf/production/client.yaml does not exist
[2016-06-09 18:58:36 +0000] com.twitter.heron.common.config.ConfigReader FINE:  Config file /home/ajorgensen/heron-client/conf/production/packing.yaml does not exist
[2016-06-09 18:58:36 +0000] com.twitter.heron.common.config.ConfigReader FINE:  Config file /home/ajorgensen/heron-client/conf/production/scheduler.yaml does not exist
[2016-06-09 18:58:36 +0000] com.twitter.heron.common.config.ConfigReader FINE:  Config file /home/ajorgensen/heron-client/conf/production/statemgr.yaml does not exist
[2016-06-09 18:58:36 +0000] com.twitter.heron.common.config.ConfigReader FINE:  Config file /home/ajorgensen/heron-client/conf/production/uploader.yaml does not exist
[2016-06-09 18:58:36 +0000] com.twitter.heron.common.config.ConfigReader FINE:  Reading config file /home/ajorgensen/heron-client/release.yaml
[2016-06-09 18:58:36 +0000] com.twitter.heron.common.config.ConfigReader FINE:  Successfully read config file /home/ajorgensen/heron-client/release.yaml
[2016-06-09 18:58:36 +0000] com.twitter.heron.common.config.ConfigReader FINE:  Reading config file /tmp/tmpreYOcn/override.yaml
[2016-06-09 18:58:36 +0000] com.twitter.heron.common.config.ConfigReader FINE:  Successfully read config file /tmp/tmpreYOcn/override.yaml
```

So I think we can do two things here, first is make the classloader exception message a little more descriptive. Secondly we should either supply defaults or fail the command if a required config file does not exist. In this case we could default to the NullUploader in the event that the uploader.yaml file is not supplied which would circumvent the exception case. I still think making the exception better is worthwhile because if the class for the uploader is provided but mistyped they'll still hit that exception path.

**Comment by maosongfu** [comment]
Another alternative can be: have a config-checker and throw meaningful exceptions if required config is not provided.

**Comment by billonahill** [comment]
@maosongfu we'll also need to do checks with reflection to make sure classes are present.
