### ISSUE TITLE
FieldsGrouping error when running Topology locally

### ISSUE THREAD

**Issue by mt830813** [twitter/heron#904]
Update from storm, changed pom, build code, every thing looks fine.
But when I try start topology locally.
Throw an exception caused by FieldsGrouping

> java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at java.util.Collections$UnmodifiableList.get(Collections.java:1309)
	at com.twitter.heron.api.generated.TopologyAPI$StreamSchema.getKeys(TopologyAPI.java:1042)
	at com.twitter.heron.simulator.grouping.FieldsGrouping.<init>(FieldsGrouping.java:34)
	at com.twitter.heron.simulator.grouping.Grouping.create(Grouping.java:38)
	at com.twitter.heron.simulator.utils.StreamConsumers.newConsumer(StreamConsumers.java:97)
	at com.twitter.heron.simulator.utils.StreamConsumers.populateStreamConsumers(StreamConsumers.java:87)
	at com.twitter.heron.simulator.executors.StreamExecutor.<init>(StreamExecutor.java:64)
	at com.twitter.heron.simulator.Simulator.submitTopology(Simulator.java:110)

Checked the code in
heron/simulator/src/java/com/twitter/heron/simulator/grouping/FieldsGrouping.java 

found those code start line 31

 `
for (int i = 0; i < schema.getKeysCount(); i++) {
      for (int j = 0; i < inputStream.getGroupingFields().getKeysCount(); j++) {
        Boolean keysEqual = schema.getKeys(i).getKey().equals(
            inputStream.getGroupingFields().getKeys(j).getKey());
        if (keysEqual) {
          fieldsGroupingIndices.add(i);
          break;
        }
      }
    }
`
Is there some typo mistake, should using j instead of i in the second for loop?

looking forward anyone's reply.
Thanks

**Comment by maosongfu** [comment]
Hi, 
It is a typo. Pull request to fix is here: https://github.com/twitter/heron/pull/907

**Comment by maosongfu** [comment]
Fixed: #907
