### ISSUE TITLE
version and timestamp in release.yaml is not loaded as String

### ISSUE THREAD

**Issue by nlu90** [twitter/heron#920]
A recent travis ci job failed with the following exception:
```bash
Exception in thread "main" java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
	at com.twitter.heron.spi.common.Config.getStringValue(Config.java:61)
	at com.twitter.heron.spi.common.Context.buildVersion(Context.java:43)
	at com.twitter.heron.scheduler.LaunchRunner.createExecutionState(LaunchRunner.java:56)
	at com.twitter.heron.scheduler.LaunchRunner.call(LaunchRunner.java:144)
	at com.twitter.heron.scheduler.SubmitterMain.callLauncherRunner(SubmitterMain.java:465)
	at com.twitter.heron.scheduler.SubmitterMain.submitTopology(SubmitterMain.java:418)
	at com.twitter.heron.scheduler.SubmitterMain.main(SubmitterMain.java:315)
```

It's due to the value of `heron.build.version` contains only numbers

```bash
See http://heronstreaming.io/docs/getting-started for how to use Heron.
heron.build.version : 5943249
heron.build.time : Wed Jun 15 00:56:13 UTC 2016
heron.build.timestamp : 1465952173000
heron.build.host : testing-gce-0bbbc5a5-20a6-4849-ae8c-ff20341cdc6c
heron.build.user : travis
heron.build.git.revision : 59432499872f8488df79ae976cb63e9f6ac8d8de
heron.build.git.status : Modified
```

Since `5943249` contains only numbers, yaml loads it as an Integer instead of a String. Then when it's used later as a string, the above exception happens. 

The `heron.build.timestamp` has the similar issue, yaml loads it as a Long instead of a String.

The solution is wrapping the values of `heron.build.version` and `heron.build.timestamp` with single or double quotes to force them to be String.

**Comment by kramasamy** [comment]
@nlu90 - thanks for tracking this. can you fix and send a PR?

**Comment by billonahill** [comment]
Should timestamp actually be a number?
